export const animals = [
    'Aardvark',
    'Aardwolf',
    'Aba roundleaf bat',
    'Abbott\'s duiker',
    'Aberdare mole shrew',
    'Abert\'s squirrel',
    'Abo bat',
    'Abyssinian hare',
    'Acacia rat',
    'Aceramarca gracile opossum',
    'Acuminate horseshoe bat',
    'Addax',
    'Admiralty Island cuscus',
    'Admiralty flying fox',
    'Aellen\'s roundleaf bat',
    'Afghan pika',
    'African black shrew',
    'African brush-tailed porcupine',
    'African buffalo',
    'African bush elephant',
    'African civet',
    'African clawless otter',
    'African dusky shrew',
    'African forest elephant',
    'African giant shrew',
    'African golden cat',
    'African grass rat',
    'African palm civet',
    'African pygmy mouse',
    'African pygmy squirrel',
    'African savanna hare',
    'African sheath-tailed bat',
    'African striped weasel',
    'African wild dog',
    'African yellow bat',
    'Agile antechinus',
    'Agile gibbon',
    'Agile gracile opossum',
    'Agile mangabey',
    'Agile wallaby',
    'Ahmanson\'s sportive lemur',
    'Alashan ground squirrel',
    'Alaska marmot',
    'Alaska moose',
    'Alaska tiny shrew',
    'Alaskan hare',
    'Aldabra flying fox',
    'Alexander\'s kusimanse',
    'Alexandria false antechinus',
    'Algerian mouse',
    'Allegheny woodrat',
    'Allen\'s big-eared bat',
    'Allen\'s chipmunk',
    'Allen\'s squirrel',
    'Allen\'s striped bat',
    'Allen\'s swamp monkey',
    'Allen\'s yellow bat',
    'Allied rock-wallaby',
    'Alpine chipmunk',
    'Alpine field mouse',
    'Alpine ibex',
    'Alpine long-eared bat',
    'Alpine marmot',
    'Alpine musk deer',
    'Alpine pika',
    'Alpine shrew',
    'Alpine woolly rat',
    'Alston\'s brown mouse',
    'Alston\'s mouse opossum',
    'Altai mole',
    'Altiplano chinchilla mouse',
    'Amami rabbit',
    'Amazon bamboo rat',
    'Amazon black howler',
    'Amazon weasel',
    'Amazonian brown brocket',
    'Amazonian red-sided opossum',
    'Amber Mountain fork-marked lemur',
    'American badger',
    'American bison',
    'American black bear',
    'American hog-nosed skunk',
    'American marten',
    'American mink',
    'American pika',
    'American pygmy shrew',
    'American red squirrel',
    'American shrew mole',
    'American water shrew',
    'Amur hedgehog',
    'Amur leopard',
    'Andaman horseshoe bat',
    'Andaman shrew',
    'Andaman spiny shrew',
    'Andean caenolestid',
    'Andean mountain cat',
    'Andean white-eared opossum',
    'Andersen\'s fruit-eating bat',
    'Andersen\'s naked-backed fruit bat',
    'Anderson\'s four-eyed opossum',
    'Anderson\'s shrew',
    'Anderson\'s squirrel',
    'Angola colobus',
    'Angolan epauletted fruit bat',
    'Angolan free-tailed bat',
    'Angolan genet',
    'Angolan kusimanse',
    'Angolan rousette',
    'Angolan talapoin',
    'Ankarana sportive lemur',
    'Ansell\'s mole-rat',
    'Ansell\'s shrew',
    'Ansorge\'s free-tailed bat',
    'Antarctic fur seal',
    'Antelope jackrabbit',
    'Antillean fruit-eating bat',
    'Antillean ghost-faced bat',
    'Antilopine kangaroo',
    'Antioquian sac-winged bat',
    'Apennine shrew',
    'Appalachian cottontail',
    'Aquatic genet',
    'Arabian leopard',
    'Arabian oryx',
    'Arabian sand gazelle',
    'Arabian shrew',
    'Arabian tahr',
    'Aratathomas\'s yellow-shouldered bat',
    'Arctic fox',
    'Arctic ground squirrel',
    'Arctic hare',
    'Arctic lemming',
    'Arctic shrew',
    'Arcuate horseshoe bat',
    'Arends\'s golden mole',
    'Argali',
    'Argentine brown bat',
    'Argentine fat-tailed mouse opossum',
    'Arizona cotton rat',
    'Arizona myotis',
    'Arizona shrew',
    'Armored rat',
    'Arnhem leaf-nosed bat',
    'Arnhem sheath-tailed bat',
    'Arnhold\'s mouse lemur',
    'Aru flying fox',
    'Arunachal macaque',
    'Ashy-headed flying fox',
    'Ashy black titi',
    'Ashy roundleaf bat',
    'Asian badger',
    'Asian barbastelle',
    'Asian black bear',
    'Asian elephant',
    'Asian garden dormouse',
    'Asian golden cat',
    'Asian gray shrew',
    'Asian highland shrew',
    'Asian house shrew',
    'Asian lesser white-toothed shrew',
    'Asian palm civet',
    'Asian particolored bat',
    'Asian red-cheeked squirrel',
    'Asiatic brush-tailed porcupine',
    'Asiatic cheetah',
    'Asiatic lion',
    'Asiatic long-tailed climbing mouse',
    'Asiatic short-tailed shrew',
    'Assam macaque',
    'Assam mole shrew',
    'Atacama myotis',
    'Atherton antechinus',
    'Atlantic Forest climbing mouse',
    'Atlantic humpback dolphin',
    'Atlantic titi',
    'Atlantic white-sided dolphin',
    'Attwater\'s pocket gopher',
    'Australian sea lion',
    'Australian snubfin dolphin',
    'Australian swamp rat',
    'Aye-aye',
    'Azara\'s night monkey',
    'Azaras\'s capuchin',
    'Azores noctule',
    'Aztec fruit-eating bat',
    'Aztec mastiff bat',
    'Aztec mouse',
    'Azuero spider monkey',
    'Azumi shrew',
    'Babault\'s mouse shrew',
    'Back-striped weasel',
    'Bagobo rat',
    'Bahamian hutia',
    'Baiji',
    'Baikal seal',
    'Bailey\'s pocket mouse',
    'Bailey\'s shrew',
    'Baird\'s pocket gopher',
    'Baird\'s shrew',
    'Bala tube-nosed bat',
    'Bald uakari',
    'Bale Mountains vervet',
    'Bale shrew',
    'Balkan lynx',
    'Balkan mole',
    'Balkan snow vole',
    'Balochistan gerbil',
    'Banana bat',
    'Banded hare-wallaby',
    'Banded linsang',
    'Banded mongoose',
    'Banded palm civet',
    'Banggai cuscus',
    'Bangs\'s mountain squirrel',
    'Bank vole',
    'Banks flying fox',
    'Banner-tailed kangaroo rat',
    'Banteng',
    'Baptista Lake titi',
    'Barasingha',
    'Barbary ground squirrel',
    'Barbary macaque',
    'Barbary sheep',
    'Barbary striped grass mouse',
    'Bare-backed rousette',
    'Bare-bellied hedgehog',
    'Bare-eared squirrel monkey',
    'Bare-tailed woolly mouse opossum',
    'Bare-tailed woolly opossum',
    'Barren ground shrew',
    'Bartels\'s rat',
    'Bastard big-footed mouse',
    'Bat-eared fox',
    'Bates\'s pygmy antelope',
    'Bates\'s shrew',
    'Bavarian pine vole',
    'Bawean deer',
    'Bay cat',
    'Bay duiker',
    'Bearded emperor tamarin',
    'Bearded seal',
    'Beatrix\'s bat',
    'Beaufort\'s naked-backed fruit bat',
    'Beccari\'s sheath-tailed bat',
    'Beccari\'s shrew',
    'Bechstein\'s bat',
    'Beech marten',
    'Beecroft\'s flying squirrel',
    'Beijing mouse-eared bat',
    'Belding\'s ground squirrel',
    'Beluga whale',
    'Bemaraha woolly lemur',
    'Bengal fox',
    'Bengal slow loris',
    'Bengal tiger',
    'Benito roundleaf bat',
    'Bennett\'s chinchilla rat',
    'Bennett\'s tree-kangaroo',
    'Berdmore\'s ground squirrel',
    'Betsileo short-tailed rat',
    'Betsileo sportive lemur',
    'Betsileo woolly lemur',
    'Bharal',
    'Bhutan giant flying squirrel',
    'Biak glider',
    'Biak naked-backed fruit bat',
    'Biak roundleaf bat',
    'Bicolored-spined porcupine',
    'Bicolored musk shrew',
    'Bicolored roundleaf bat',
    'Bicolored shrew',
    'Bidentate yellow-eared bat',
    'Bidentate yellow-shouldered bat',
    'Big-eared brown bat',
    'Big-eared climbing rat',
    'Big-eared flying fox',
    'Big-eared horseshoe bat',
    'Big-eared opossum',
    'Big-eared woolly bat',
    'Big Mexican small-eared shrew',
    'Big bonneted bat',
    'Big brown bat',
    'Big crested mastiff bat',
    'Big free-tailed bat',
    'Big hairy armadillo',
    'Big naked-backed bat',
    'Bighorn sheep',
    'Bini free-tailed bat',
    'Binturong',
    'Bioko Allen\'s bushbaby',
    'Bioko drill',
    'Bioko forest shrew',
    'Birdlike noctule',
    'Bishop\'s slender opossum',
    'Bismarck masked flying fox',
    'Black-and-white ruffed lemur',
    'Black-backed jackal',
    'Black-bearded flying fox',
    'Black-bearded tomb bat',
    'Black-bellied fruit bat',
    'Black-capped fruit bat',
    'Black-capped marmot',
    'Black-capped squirrel monkey',
    'Black-crowned Central American squirrel monkey',
    'Black-eared flying fox',
    'Black-eared mouse',
    'Black-eared squirrel',
    'Black-flanked rock-wallaby',
    'Black-footed cat',
    'Black-footed ferret',
    'Black-footed gray langur',
    'Black-footed mongoose',
    'Black-footed shrew',
    'Black-footed tree-rat',
    'Black-fronted duiker',
    'Black-fronted titi',
    'Black-gilded pipistrelle',
    'Black-headed night monkey',
    'Black-headed spider monkey',
    'Black-mantled tamarin',
    'Black-rumped agouti',
    'Black-shanked douc',
    'Black-shouldered opossum',
    'Black-spotted cuscus',
    'Black-striped capuchin',
    'Black-striped wallaby',
    'Black-tailed dasyure',
    'Black-tailed hutia',
    'Black-tailed jackrabbit',
    'Black-tailed marmoset',
    'Black-tailed mosaic-tailed rat',
    'Black-tailed prairie dog',
    'Black-tailed tree rat',
    'Black-tufted marmoset',
    'Black-winged little yellow bat',
    'Black agouti',
    'Black and rufous elephant shrew',
    'Black bearded saki',
    'Black bonneted bat',
    'Black capuchin',
    'Black colobus',
    'Black crested mangabey',
    'Black dorcopsis',
    'Black duiker',
    'Black flying fox',
    'Black giant squirrel',
    'Black howler',
    'Black jackrabbit',
    'Black lemur',
    'Black lion tamarin',
    'Black mastiff bat',
    'Black musk deer',
    'Black myotis',
    'Black rat',
    'Black snub-nosed monkey',
    'Black squirrel monkey',
    'Black tamarin',
    'Black titi',
    'Black wallaroo',
    'Black wildebeest',
    'Blackbuck',
    'Blackish small-eared shrew',
    'Blackish white-toothed shrew',
    'Blanford\'s fox',
    'Blanford\'s fruit bat',
    'Blanford\'s rat',
    'Blasius\'s horseshoe bat',
    'Blesbok',
    'Blick\'s grass rat',
    'Blind mole',
    'Blond capuchin',
    'Blue-and-yellow macaw',
    'Blue-billed teal',
    'Blue-eyed black lemur',
    'Blue-eyed cuscus',
    'Blue-eyed spotted cuscus',
    'Blue-footed booby',
    'Blue-tongued skink',
    'Blue crane',
    'Blue duck',
    'Blue duiker',
    'Blue monkey',
    'Blue shark',
    'Blue waxbill',
    'Blue whale',
    'Blue wildebeest',
    'Blunt-eared bat',
    'Blyth\'s horseshoe bat',
    'Blyth\'s vole',
    'Boa constrictor',
    'Boat-billed heron',
    'Bobak marmot',
    'Bobcat',
    'Bogotá yellow-shouldered bat',
    'Bohor reedbuck',
    'Bokermann\'s nectar bat',
    'Bokhara horseshoe bat',
    'Bolam\'s mouse',
    'Bolivian red howler',
    'Bonda mastiff bat',
    'Bongolava mouse lemur',
    'Bonin flying fox',
    'Bonnet macaque',
    'Bonobo',
    'Bontebok',
    'Boodie',
    'Booted macaque',
    'Bornean bearded pig',
    'Bornean clouded leopard',
    'Bornean ferret-badger',
    'Bornean horseshoe bat',
    'Bornean mountain ground squirrel',
    'Bornean orangutan',
    'Bornean shrew',
    'Bornean water shrew',
    'Bornean white-bearded gibbon',
    'Borneo black-banded squirrel',
    'Borneo elephant',
    'Borneo fruit bat',
    'Borneo roundleaf bat',
    'Botta\'s pocket gopher',
    'Bottlenose dolphin',
    'Bougainville monkey-faced bat',
    'Bourlon\'s genet',
    'Bourret\'s horseshoe bat',
    'Bouvier\'s red colobus',
    'Bower\'s white-toothed rat',
    'Bowhead whale',
    'Brandt\'s bat',
    'Brandt\'s hedgehog',
    'Brandt\'s vole',
    'Brants\'s whistling rat',
    'Brazilian big-eyed bat',
    'Brazilian brown bat',
    'Brazilian funnel-eared bat',
    'Brazilian gracile opossum',
    'Brazilian guinea pig',
    'Brazilian porcupine',
    'Brazilian slender opossum',
    'Brazilian squirrel',
    'Brazilian three-banded armadillo',
    'Bridled nail-tail wallaby',
    'Bristle-spined rat',
    'Broad-eared bat',
    'Broad-eared horseshoe bat',
    'Broad-footed mole',
    'Broad-striped Malagasy mongoose',
    'Broad-striped dasyure',
    'Broad-striped tube-nosed fruit bat',
    'Broad-toothed mouse',
    'Broad-toothed tailless bat',
    'Brock\'s yellow-eared bat',
    'Brolga',
    'Bronze quoll',
    'Bronze tube-nosed bat',
    'Brooks\'s dyak fruit bat',
    'Broom hare',
    'Brown\'s pademelon',
    'Brown-and-yellow marshbird',
    'Brown-eared woolly opossum',
    'Brown-mantled tamarin',
    'Brown-tailed mongoose',
    'Brown-throated sloth',
    'Brown antechinus',
    'Brown bear',
    'Brown dorcopsis',
    'Brown flower bat',
    'Brown four-eyed opossum',
    'Brown fruit-eating bat',
    'Brown fur seal',
    'Brown greater galago',
    'Brown hairy dwarf porcupine',
    'Brown howler',
    'Brown hyena',
    'Brown long-eared bat',
    'Brown mastiff bat',
    'Brown mouse lemur',
    'Brown palm civet',
    'Brown pelican',
    'Brown pipistrelle',
    'Brown rat',
    'Brown spider monkey',
    'Brown tent-making bat',
    'Brown titi',
    'Brown weeper capuchin',
    'Brown woolly monkey',
    'Brumback\'s night monkey',
    'Brush-tailed mulgara',
    'Brush-tailed phascogale',
    'Brush-tailed rabbit rat',
    'Brush-tailed rock-wallaby',
    'Brush mouse',
    'Brush rabbit',
    'Buchara shrew',
    'Buettikofer\'s epauletted fruit bat',
    'Buettikofer\'s shrew',
    'Buffy-headed marmoset',
    'Buffy-tufted marmoset',
    'Buffy broad-nosed bat',
    'Buffy flower bat',
    'Bulmer\'s fruit bat',
    'Bunny rat',
    'Bunyoro rabbit',
    'Burmese ferret-badger',
    'Burmese hare',
    'Burmese short-tailed shrew',
    'Burmese whiskered bat',
    'Burrowing owl',
    'Buru babirusa',
    'Bush dog',
    'Bush rat',
    'Bush vlei rat',
    'Bushpig',
    'Bushveld elephant shrew',
    'Bushveld gerbil',
    'Bushveld horseshoe bat',
    'Bushy-tailed jird',
    'Bushy-tailed mongoose',
    'Bushy-tailed opossum',
    'Bushy-tailed woodrat',
    'Butiaba naked-tailed shrew',
    'Cabrera\'s hutia',
    'Cabrera\'s vole',
    'Cacomistle',
    'Cactus mouse',
    'Cadorna\'s pipistrelle',
    'Cairo spiny mouse',
    'Calabar angwantibo',
    'Calaby\'s pademelon',
    'Calamian deer',
    'California chipmunk',
    'California ground squirrel',
    'California leaf-nosed bat',
    'California mouse',
    'California myotis',
    'California pocket mouse',
    'California sea lion',
    'California vole',
    'Camas pocket gopher',
    'Cambodian striped squirrel',
    'Cameroon scaly-tail',
    'Cameroonian forest shrew',
    'Cameroonian shrew',
    'Camiguin forest rat',
    'Campbell\'s dwarf hamster',
    'Campbell\'s mona monkey',
    'Campo flicker',
    'Canada goose',
    'Canada lynx',
    'Canarian shrew',
    'Canary big-eared bat',
    'Cantor\'s roundleaf bat',
    'Canut\'s horseshoe bat',
    'Cape Barren goose',
    'Cape York rock-wallaby',
    'Cape cobra',
    'Cape dune mole-rat',
    'Cape elephant shrew',
    'Cape fox',
    'Cape genet',
    'Cape golden mole',
    'Cape gray mongoose',
    'Cape ground squirrel',
    'Cape grysbok',
    'Cape hairy bat',
    'Cape hare',
    'Cape horseshoe bat',
    'Cape mole-rat',
    'Cape porcupine',
    'Cape serotine',
    'Cape short-eared gerbil',
    'Cape spiny mouse',
    'Cape starling',
    'Cape white-eye',
    'Capped langur',
    'Capybara',
    'Caquetá titi',
    'Caracal',
    'Carmen Mountain shrew',
    'Caroline flying fox',
    'Carpentarian dunnart',
    'Carriker\'s round-eared bat',
    'Cascade golden-mantled ground squirrel',
    'Caspian seal',
    'Cattle egret',
    'Caucasian mole',
    'Caucasian pygmy shrew',
    'Caucasian shrew',
    'Caucasian squirrel',
    'Cave myotis',
    'Cave nectar bat',
    'Celebes crested macaque',
    'Celebes rat',
    'Celebes warty pig',
    'Central African red colobus',
    'Central American agouti',
    'Central American dwarf squirrel',
    'Central American squirrel monkey',
    'Central chimpanzee',
    'Central netted dragon',
    'Central rock rat',
    'Centralian blue-tongued skink',
    'Ceram fruit bat',
    'Chacma baboon',
    'Chacoan gracile opossum',
    'Chacoan mara',
    'Chacoan naked-tailed armadillo',
    'Chacoan peccary',
    'Chacoan pygmy opossum',
    'Chamois',
    'Chapin\'s free-tailed bat',
    'Charming thicket rat',
    'Checkered elephant shrew',
    'Cheesman\'s gerbil',
    'Cheetah',
    'Chestnut-bellied shrew',
    'Chestnut-bellied titi',
    'Chestnut climbing mouse',
    'Chestnut long-tongued bat',
    'Chestnut sac-winged bat',
    'Chestnut short-tailed bat',
    'Chestnut weaver',
    'Chestnut white-bellied rat',
    'Chilean dolphin',
    'Chilean flamingo',
    'Chilean myotis',
    'Chilean rock rat',
    'Chimpanzee',
    'Chinese bamboo rat',
    'Chinese ferret-badger',
    'Chinese giant flying squirrel',
    'Chinese goral',
    'Chinese hare',
    'Chinese highland shrew',
    'Chinese mole shrew',
    'Chinese mountain cat',
    'Chinese noctule',
    'Chinese pangolin',
    'Chinese pygmy dormouse',
    'Chinese red pika',
    'Chinese rufous horseshoe bat',
    'Chinese shrew mole',
    'Chinese striped hamster',
    'Chinese water dragon',
    'Chinese water myotis',
    'Chinese water shrew',
    'Chinese zokor',
    'Chinkara',
    'Chiriquinan serotine',
    'Chisel-toothed kangaroo rat',
    'Chital',
    'Chlamydosaurus',
    'Choco broad-nosed bat',
    'Chocolate wattled bat',
    'Christmas Island shrew',
    'Chuckwalla',
    'Cinderella fat-tailed mouse opossum',
    'Cinderella shrew',
    'Cinereus ringtail possum',
    'Cinereus shrew',
    'Cinnamon antechinus',
    'Cinnamon myotis',
    'Cinnamon red bat',
    'Clara\'s echymipera',
    'Clark\'s nutcracker',
    'Clear-winged woolly bat',
    'Cliff chipmunk',
    'Climbing shrew',
    'Clouded leopard',
    'Coast mole',
    'Coastal black-handed titi',
    'Coastal sheath-tailed bat',
    'Coiban agouti',
    'Coiban mastiff bat',
    'Coimbra Filho\'s titi',
    'Coke\'s hartebeest',
    'Collared brown lemur',
    'Collared lemming',
    'Collared mangabey',
    'Collared mongoose',
    'Collared peccary',
    'Collared pika',
    'Collared pipistrelle',
    'Collared titi',
    'Collared tuco-tuco',
    'Collie\'s squirrel',
    'Colombian black-handed titi',
    'Colombian bonneted bat',
    'Colombian red howler',
    'Colombian small-eared shrew',
    'Colombian spider monkey',
    'Colombian weasel',
    'Colombian woolly monkey',
    'Colorado chipmunk',
    'Coluber constrictor anthicus',
    'Coluber constrictor foxii',
    'Columbian ground squirrel',
    'Comb duck',
    'Commissaris\'s long-tongued bat',
    'Common bent-wing bat',
    'Common big-eared bat',
    'Common blossom bat',
    'Common bottlenose dolphin',
    'Common brown lemur',
    'Common brushtail possum',
    'Common collared lizard',
    'Common dolphin',
    'Common duiker',
    'Common dwarf mongoose',
    'Common echymipera',
    'Common eland',
    'Common fat-tailed mouse opossum',
    'Common genet',
    'Common goldeneye',
    'Common gundi',
    'Common kusimanse',
    'Common marmoset',
    'Common minke whale',
    'Common mole-rat',
    'Common myna',
    'Common nighthawk',
    'Common noctule',
    'Common opossum',
    'Common pheasant',
    'Common pipistrelle',
    'Common planigale',
    'Common punaré',
    'Common ringtail possum',
    'Common sheath-tailed bat',
    'Common shelduck',
    'Common shrew',
    'Common spotted cuscus',
    'Common squirrel monkey',
    'Common thick-thumbed bat',
    'Common treeshrew',
    'Common tsessebe',
    'Common tube-nosed fruit bat',
    'Common vampire bat',
    'Common vole',
    'Common wallaroo',
    'Common warthog',
    'Common wombat',
    'Common wood pigeon',
    'Comoro rousette',
    'Complex-toothed flying squirrel',
    'Congo clawless otter',
    'Congo rope squirrel',
    'Congo white-toothed shrew',
    'Coppery pipistrelle',
    'Coppery ringtail possum',
    'Coppery titi',
    'Coquerel\'s giant mouse lemur',
    'Coquerel\'s sifaka',
    'Coqui francolin',
    'Corsac fox',
    'Corsican hare',
    'Coruro',
    'Cotton-top tamarin',
    'Cotton mouse',
    'Cougar',
    'Cowan\'s shrew tenrec',
    'Cox\'s roundleaf bat',
    'Coyote',
    'Coypu',
    'Cozumel harvest mouse',
    'Cozumel raccoon',
    'Cozumelan golden bat',
    'Crab-eating fox',
    'Crab-eating macaque',
    'Crab-eating mongoose',
    'Crab-eating raccoon',
    'Crab-eating rat',
    'Crabeater seal',
    'Crawford\'s gray shrew',
    'Creagh\'s horseshoe bat',
    'Cream-coloured giant squirrel',
    'Creeping vole',
    'Crest-tailed mulgara',
    'Crested barbet',
    'Crested bunting',
    'Crested capuchin',
    'Crested porcupine',
    'Crested servaline genet',
    'Cretan shrew',
    'Crimson-breasted shrike',
    'Croslet horseshoe bat',
    'Cross River gorilla',
    'Crosse\'s shrew',
    'Crotalus cerastes',
    'Crown-of-thorns starfish',
    'Crowned eagle',
    'Crowned lemur',
    'Crowned shrew',
    'Crowned sifaka',
    'Cruz Lima\'s saddle-back tamarin',
    'Ctenophorus ornatus',
    'Cuban fig-eating bat',
    'Cuban flower bat',
    'Cuban fruit-eating bat',
    'Cuban funnel-eared bat',
    'Cuban greater funnel-eared bat',
    'Cuban solenodon',
    'Culpeo',
    'Curacao myotis',
    'Curve-billed thrasher',
    'Cutch rat',
    'Cuvier\'s beaked whale',
    'Cuvier\'s gazelle',
    'Cyclops roundleaf bat',
    'Cyrenaica shrew',
    'D\'Orbigny\'s tuco-tuco',
    'Dall\'s porpoise',
    'Dall sheep',
    'Dalton\'s mouse',
    'Dama gazelle',
    'Damaraland mole-rat',
    'Daraina sportive lemur',
    'Darién small-eared shrew',
    'Dark-footed mouse shrew',
    'Dark-nosed small-footed myotis',
    'Dark-tailed tree rat',
    'Dark-winged lesser house bat',
    'Dark-winged trumpeter',
    'Dark fruit-eating bat',
    'Dark long-tongued bat',
    'Dark sheath-tailed bat',
    'Darling\'s horseshoe bat',
    'Darwin\'s fox',
    'Darwin\'s leaf-eared mouse',
    'Dassie rat',
    'Daubenton\'s bat',
    'Daurian hedgehog',
    'Daurian pika',
    'David\'s echymipera',
    'David\'s myotis',
    'Davies\'s big-eared bat',
    'Davis\'s round-eared bat',
    'Davy\'s naked-backed bat',
    'Day\'s shrew',
    'Dayak fruit bat',
    'Dayak roundleaf bat',
    'De Brazza\'s monkey',
    'De Winton\'s golden mole',
    'De Winton\'s shrew',
    'Decken\'s horseshoe bat',
    'Dekeyser\'s nectar bat',
    'Delacour\'s langur',
    'Delacour\'s marmoset rat',
    'Delany\'s mouse',
    'Delicate slender opossum',
    'Deltaic four-eyed opossum',
    'Denham\'s bustard',
    'Dent\'s horseshoe bat',
    'Dent\'s mona monkey',
    'Dent\'s shrew',
    'Deppe\'s squirrel',
    'Derby\'s woolly opossum',
    'Desert cottontail',
    'Desert hare',
    'Desert hedgehog',
    'Desert kangaroo rat',
    'Desert long-eared bat',
    'Desert mouse',
    'Desert musk shrew',
    'Desert pocket gopher',
    'Desert pocket mouse',
    'Desert pygmy mouse',
    'Desert red bat',
    'Desert tortoise',
    'Desert warthog',
    'Desert woodrat',
    'Desmarest\'s hutia',
    'Desmarest\'s spiny pocket mouse',
    'Desperate shrew',
    'Dhole',
    'Diadem leaf-nosed bat',
    'Diademed sifaka',
    'Dian\'s tarsier',
    'Diana monkey',
    'Dibatag',
    'Dibbler',
    'Dinagat bushy-tailed cloud rat',
    'Dinagat gymnure',
    'Dingiso',
    'Dingo',
    'Dobson\'s epauletted fruit bat',
    'Dobson\'s horseshoe bat',
    'Dobson\'s shrew tenrec',
    'Dominican myotis',
    'Dorcas gazelle',
    'Doria\'s tree-kangaroo',
    'Dormouse tufted-tailed rat',
    'Dorothy\'s slender opossum',
    'Douglas squirrel',
    'Downy woodpecker',
    'Drill',
    'Dromedary',
    'Drouhard\'s shrew tenrec',
    'Dryad shrew tenrec',
    'Dryas monkey',
    'Drylands vesper mouse',
    'Dsinezumi shrew',
    'Dusky-footed woodrat',
    'Dusky antechinus',
    'Dusky bushbaby',
    'Dusky caenolestid',
    'Dusky fruit bat',
    'Dusky leaf-nosed bat',
    'Dusky leaf monkey',
    'Dusky pademelon',
    'Dusky pipistrelle',
    'Duthie\'s golden mole',
    'Dwarf bonneted bat',
    'Dwarf brocket',
    'Dwarf dog-faced bat',
    'Dwarf fat-tailed mouse opossum',
    'Dwarf gymnure',
    'Dwarf little fruit bat',
    'Dwarf musk deer',
    'Dwarf scaly-tailed squirrel',
    'Dwarf shrew',
    'Ear-spot squirrel',
    'East African epauletted fruit bat',
    'East African highland shrew',
    'East African little collared fruit bat',
    'East African oryx',
    'East Asian tailless leaf-nosed bat',
    'Eastern barred bandicoot',
    'Eastern bettong',
    'Eastern black crested gibbon',
    'Eastern box turtle',
    'Eastern cave bat',
    'Eastern chestnut mouse',
    'Eastern chimpanzee',
    'Eastern chipmunk',
    'Eastern common cuscus',
    'Eastern cottontail',
    'Eastern diamondback rattlesnake',
    'Eastern forest bat',
    'Eastern gorilla',
    'Eastern gray squirrel',
    'Eastern grey kangaroo',
    'Eastern harvest mouse',
    'Eastern heather vole',
    'Eastern hoolock gibbon',
    'Eastern indigo snake',
    'Eastern lesser bamboo lemur',
    'Eastern long-beaked echidna',
    'Eastern long-eared bat',
    'Eastern long-fingered bat',
    'Eastern long-necked turtle',
    'Eastern lowland gorilla',
    'Eastern lowland olingo',
    'Eastern mole',
    'Eastern pygmy marmoset',
    'Eastern pygmy possum',
    'Eastern quoll',
    'Eastern racer',
    'Eastern red bat',
    'Eastern rock elephant shrew',
    'Eastern small-footed myotis',
    'Eastern spiny mouse',
    'Eastern spotted skunk',
    'Eastern tube-nosed bat',
    'Eastern voalavo',
    'Eastern wolf',
    'Eastern woodrat',
    'Eastern woolly lemur',
    'Eastern yellow-billed hornbill',
    'Echigo mole',
    'Ecuadorian mantled howler',
    'Ecuadorian sac-winged bat',
    'Ecuadorian squirrel monkey',
    'Edible dormouse',
    'Ega long-tongued bat',
    'Egyptian cobra',
    'Egyptian free-tailed bat',
    'Egyptian fruit bat',
    'Egyptian goose',
    'Egyptian mongoose',
    'Egyptian slit-faced bat',
    'Egyptian tomb bat',
    'Egyptian vulture',
    'Egyptian weasel',
    'Eisentraut\'s mouse shrew',
    'Eisentraut\'s shrew',
    'Eld\'s deer',
    'Elegant crested tinamou',
    'Elegant fat-tailed mouse opossum',
    'Elegant myotis',
    'Elegant water shrew',
    'Elgon shrew',
    'Elk',
    'Elliot\'s short-tailed shrew',
    'Elongated shrew',
    'Eloquent horseshoe bat',
    'Emerald-spotted wood dove',
    'Emerald tree boa',
    'Emerald tree monitor',
    'Emilia\'s short-tailed opossum',
    'Emin\'s pouched rat',
    'Emperor tamarin',
    'Emu',
    'Enders\'s small-eared shrew',
    'Endo\'s pipistrelle',
    'Epicrates maurus',
    'Equatorial dog-faced bat',
    'Equatorial saki',
    'Ernst Mayr\'s water rat',
    'Ethiopian amphibious rat',
    'Ethiopian dwarf mongoose',
    'Ethiopian epauletted fruit bat',
    'Ethiopian highland hare',
    'Ethiopian large-eared roundleaf bat',
    'Ethiopian white-footed mouse',
    'Ethiopian wolf',
    'Etruscan shrew',
    'Eurasian beaver',
    'Eurasian harvest mouse',
    'Eurasian hoopoe',
    'Eurasian least shrew',
    'Eurasian lynx',
    'Eurasian pygmy shrew',
    'Eurasian spoonbill',
    'Eurasian water shrew',
    'European badger',
    'European bison',
    'European free-tailed bat',
    'European ground squirrel',
    'European hamster',
    'European hare',
    'European hedgehog',
    'European herring gull',
    'European mink',
    'European mole',
    'European pine marten',
    'European pine vole',
    'European polecat',
    'European rabbit',
    'European snow vole',
    'European water vole',
    'European wildcat',
    'Evening bat',
    'Fallow deer',
    'Far Eastern myotis',
    'Fat-tailed dunnart',
    'Fat-tailed dwarf lemur',
    'Fat-tailed false antechinus',
    'Fat-tailed gerbil',
    'Fawn-footed mosaic-tailed rat',
    'Fawn antechinus',
    'Fawn hopping mouse',
    'Fawn leaf-nosed bat',
    'Feather-tailed possum',
    'Feathertail glider',
    'Fennec fox',
    'Feral pigeon',
    'Fernandez\'s sword-nosed bat',
    'Ferruginous hawk',
    'Field vole',
    'Fijian mastiff bat',
    'Fijian monkey-faced bat',
    'Fin whale',
    'Findley\'s myotis',
    'Finlayson\'s squirrel',
    'Finless porpoise',
    'Fire-footed rope squirrel',
    'Fischer\'s guiara',
    'Fischer\'s little fruit bat',
    'Fischer\'s pygmy fruit bat',
    'Fishing cat',
    'Flat-faced fruit-eating bat',
    'Flat-headed cat',
    'Flat-headed kusimanse',
    'Flat-headed myotis',
    'Flat-skulled shrew',
    'Flightless cormorant',
    'Flores giant rat',
    'Flores shrew',
    'Florida bonneted bat',
    'Flute-nosed bat',
    'Fly River water rat',
    'Fog shrew',
    'Forest dormouse',
    'Forest giant squirrel',
    'Forest pipistrelle',
    'Fork-tailed drongo',
    'Formosan rock macaque',
    'Formosan woolly horseshoe bat',
    'Forrest\'s pika',
    'Fossorial giant rat',
    'Four-horned antelope',
    'Four-spotted chaser',
    'Four-striped grass mouse',
    'Four-toed elephant shrew',
    'Four-toed hedgehog',
    'Four-toed jerboa',
    'Fox\'s shrew',
    'Fox squirrel',
    'Franklin\'s ground squirrel',
    'Franquet\'s epauletted fruit bat',
    'François\' langur',
    'Fraser\'s dolphin',
    'Fraser\'s musk shrew',
    'Fraternal fruit-eating bat',
    'Fresno kangaroo rat',
    'Fringe-eared oryx',
    'Fringe-lipped bat',
    'Fringed fruit-eating bat',
    'Fringed myotis',
    'Frosted myotis',
    'Frosted sac-winged bat',
    'Fulvus roundleaf bat',
    'Fynbos golden mole',
    'Gabon bushbaby',
    'Gabon talapoin',
    'Gairdner\'s shrewmouse',
    'Galah',
    'Galapagos hawk',
    'Galapagos land iguana',
    'Galapagos penguin',
    'Galápagos dove',
    'Galápagos fur seal',
    'Galápagos mockingbird',
    'Galápagos sea lion',
    'Galápagos tortoise',
    'Gambel\'s quail',
    'Gambian epauletted fruit bat',
    'Gambian mongoose',
    'Gambian pouched rat',
    'Gambian sun squirrel',
    'Gansu mole',
    'Gansu pika',
    'Garden dormouse',
    'Gaur',
    'Geata mouse shrew',
    'Gebe cuscus',
    'Gee\'s golden langur',
    'Geelvink Bay flying fox',
    'Gelada',
    'Gemsbok',
    'Genoways\'s yellow bat',
    'Geoffroy\'s bat',
    'Geoffroy\'s cat',
    'Geoffroy\'s horseshoe bat',
    'Geoffroy\'s rousette',
    'Geoffroy\'s spider monkey',
    'Geoffroy\'s tailless bat',
    'Geoffroy\'s tamarin',
    'Gerenuk',
    'Gerp\'s mouse lemur',
    'Gervais\'s fruit-eating bat',
    'Gervais\'s funnel-eared bat',
    'Ghost-faced bat',
    'Ghost bat',
    'Giant anteater',
    'Giant armadillo',
    'Giant bandicoot',
    'Giant bushy-tailed cloud rat',
    'Giant eland',
    'Giant forest genet',
    'Giant forest hog',
    'Giant girdled lizard',
    'Giant golden-crowned flying fox',
    'Giant golden mole',
    'Giant kangaroo rat',
    'Giant muntjac',
    'Giant otter',
    'Giant otter shrew',
    'Giant panda',
    'Giant roundleaf bat',
    'Giant sable antelope',
    'Giant white-tailed rat',
    'Gila monster',
    'Gilbert\'s dunnart',
    'Gilbert\'s potoroo',
    'Gilded tube-nosed bat',
    'Giraffe',
    'Glass\'s shrew',
    'Glen\'s long-fingered bat',
    'Glossy ibis',
    'Glover\'s pika',
    'Gmelin\'s white-toothed shrew',
    'Gnome fruit-eating bat',
    'Goa',
    'Godman\'s long-tailed bat',
    'Godman\'s rock-wallaby',
    'Goeldi\'s marmoset',
    'Goitered gazelle',
    'Golden-backed tree-rat',
    'Golden-bellied capuchin',
    'Golden-bellied treeshrew',
    'Golden-brown mouse lemur',
    'Golden-crowned sifaka',
    'Golden-faced saki',
    'Golden-headed lion tamarin',
    'Golden-mantled ground squirrel',
    'Golden-mantled howler',
    'Golden-mantled tamarin',
    'Golden-mantled tree-kangaroo',
    'Golden-rumped elephant shrew',
    'Golden-tipped bat',
    'Golden angwantibo',
    'Golden bamboo lemur',
    'Golden bandicoot',
    'Golden bat',
    'Golden eagle',
    'Golden hamster',
    'Golden jackal',
    'Golden lion tamarin',
    'Golden mouse',
    'Golden palm civet',
    'Golden snub-nosed monkey',
    'Golden spiny mouse',
    'Goldman\'s broad-clawed shrew',
    'Goldman\'s woodrat',
    'Goliath heron',
    'Goliath shrew',
    'Gomantong myotis',
    'Goodfellow\'s tree-kangaroo',
    'Goodman\'s mouse lemur',
    'Goodwin\'s broad-clawed shrew',
    'Gorontalo macaque',
    'Gould\'s long-eared bat',
    'Gould\'s wattled bat',
    'Gracile Atlantic spiny rat',
    'Gracile naked-tailed shrew',
    'Gracile shrew mole',
    'Gracile shrew tenrec',
    'Granada hare',
    'Grandidier\'s mongoose',
    'Grandidier\'s trident bat',
    'Grandidier\'s tufted-tailed rat',
    'Grant\'s bushbaby',
    'Grant\'s forest shrew',
    'Grant\'s gazelle',
    'Grant\'s golden mole',
    'Grapsus grapsus',
    'Grasse\'s shrew',
    'Gray-backed sportive lemur',
    'Gray-bellied caenolestid',
    'Gray-bellied mountain rat',
    'Gray-bellied night monkey',
    'Gray-collared chipmunk',
    'Gray-handed night monkey',
    'Gray-headed lemur',
    'Gray-shanked douc',
    'Gray-tailed vole',
    'Gray bat',
    'Gray brocket',
    'Gray dorcopsis',
    'Gray four-eyed opossum',
    'Gray fox',
    'Gray langur',
    'Gray leaf-eared mouse',
    'Gray long-tongued bat',
    'Gray marmot',
    'Gray mouse lemur',
    'Gray sac-winged bat',
    'Gray short-tailed bat',
    'Gray short-tailed opossum',
    'Gray slender loris',
    'Gray slender opossum',
    'Gray snub-nosed monkey',
    'Gray spiny mouse',
    'Gray whale',
    'Gray woolly monkey',
    'Grayish mouse opossum',
    'Great-tailed triok',
    'Great Basin pocket mouse',
    'Great cormorant',
    'Great egret',
    'Great evening bat',
    'Great flying fox',
    'Great fruit-eating bat',
    'Great gerbil',
    'Great horned owl',
    'Great jerboa',
    'Great kiskadee',
    'Great roundleaf bat',
    'Great skua',
    'Great stripe-faced bat',
    'Great white pelican',
    'Greater Asiatic yellow bat',
    'Greater Chinese mole',
    'Greater Egyptian gerbil',
    'Greater Egyptian jerboa',
    'Greater adjutant',
    'Greater bamboo bat',
    'Greater bamboo lemur',
    'Greater bandicoot rat',
    'Greater big-footed mouse',
    'Greater bilby',
    'Greater blue-eared starling',
    'Greater broad-nosed bat',
    'Greater bulldog bat',
    'Greater cane rat',
    'Greater dog-like bat',
    'Greater dwarf shrew',
    'Greater false vampire bat',
    'Greater flamingo',
    'Greater forest shrew',
    'Greater glider',
    'Greater grison',
    'Greater guinea pig',
    'Greater hedgehog tenrec',
    'Greater horseshoe bat',
    'Greater kudu',
    'Greater large-headed shrew',
    'Greater long-fingered bat',
    'Greater long-nosed armadillo',
    'Greater long-nosed bat',
    'Greater long-tailed bat',
    'Greater long-tailed shrew tenrec',
    'Greater mole-rat',
    'Greater monkey-faced bat',
    'Greater mouse-deer',
    'Greater mouse-eared bat',
    'Greater mouse-tailed bat',
    'Greater musky fruit bat',
    'Greater naked-tailed armadillo',
    'Greater noctule bat',
    'Greater red musk shrew',
    'Greater rhea',
    'Greater roadrunner',
    'Greater sac-winged bat',
    'Greater sage-grouse',
    'Greater short-nosed fruit bat',
    'Greater spear-nosed bat',
    'Greater spot-nosed monkey',
    'Greater stick-nest rat',
    'Greater stripe-backed shrew',
    'Greater tube-nosed bat',
    'Greater white-toothed shrew',
    'Greater yellow-shouldered bat',
    'Green-winged pytilia',
    'Green acouchi',
    'Green bush squirrel',
    'Green heron',
    'Green iguana',
    'Green monkey',
    'Green ringtail possum',
    'Greenhall\'s dog-faced bat',
    'Greenish naked-backed fruit bat',
    'Greenish yellow bat',
    'Greenwood\'s shrew',
    'Gregarious short-tailed rat',
    'Grewcock\'s sportive lemur',
    'Grey-bellied dunnart',
    'Grey-bellied squirrel',
    'Grey-cheeked mangabey',
    'Grey-crowned Central American squirrel monkey',
    'Grey-faced sengi',
    'Grey-headed flying fox',
    'Grey-headed swamphen',
    'Grey go-away-bird',
    'Grey heron',
    'Grey long-eared bat',
    'Grey partridge',
    'Grey red-backed vole',
    'Grey rhebok',
    'Grey seal',
    'Greylag goose',
    'Griffon vulture',
    'Grivet',
    'Grizzled giant squirrel',
    'Grizzled tree-kangaroo',
    'Grizzly bear',
    'Groove-toothed bat',
    'Groove-toothed flying squirrel',
    'Ground cuscus',
    'Groundhog',
    'Guadalcanal monkey-faced bat',
    'Guadalupe fur seal',
    'Guadeloupe big-eyed bat',
    'Guajira mouse opossum',
    'Guanaco',
    'Guatemalan black howler',
    'Guatemalan broad-clawed shrew',
    'Guayaquil squirrel',
    'Guianan spear-nosed bat',
    'Guianan squirrel monkey',
    'Guianan white-eared opossum',
    'Guinea baboon',
    'Guinean horseshoe bat',
    'Gulf Coast kangaroo rat',
    'Gunning\'s golden mole',
    'Gunnison\'s prairie dog',
    'Guramba shrew',
    'Guyanan red howler',
    'Günther\'s dik-dik',
    'Günther\'s vole',
    'Habbema dasyure',
    'Haig\'s tuco-tuco',
    'Hainan black crested gibbon',
    'Hainan gymnure',
    'Hainan hare',
    'Hairless bat',
    'Hairy-eared dwarf lemur',
    'Hairy-faced bat',
    'Hairy-footed dunnart',
    'Hairy-footed gerbil',
    'Hairy-fronted muntjac',
    'Hairy-legged myotis',
    'Hairy-legged vampire bat',
    'Hairy-nosed otter',
    'Hairy-tailed bolo mouse',
    'Hairy-tailed mole',
    'Hairy Atlantic spiny rat',
    'Hairy big-eared bat',
    'Hairy big-eyed bat',
    'Hairy fruit-eating bat',
    'Hairy little fruit bat',
    'Hairy slit-faced bat',
    'Hairy yellow-shouldered bat',
    'Halcyon horseshoe bat',
    'Halmahera blossom bat',
    'Halmahera naked-backed fruit bat',
    'Hamadryas baboon',
    'Hamlyn\'s monkey',
    'Hammer-headed bat',
    'Handley\'s nectar bat',
    'Handley\'s slender opossum',
    'Handley\'s tailless bat',
    'Harbor seal',
    'Harbour porpoise',
    'Hardwicke\'s woolly bat',
    'Harenna shrew',
    'Harlequin bat',
    'Harmless serotine',
    'Harnessed bushbuck',
    'Harp seal',
    'Harpy fruit bat',
    'Harris\'s antelope squirrel',
    'Harrison\'s tube-nosed bat',
    'Hartebeest',
    'Harvey\'s duiker',
    'Hastings River mouse',
    'Hatinh langur',
    'Hatt\'s vesper rat',
    'Hawaiian monk seal',
    'Hawks\' sportive lemur',
    'Hazel dormouse',
    'Heart-nosed bat',
    'Heck\'s macaque',
    'Hector\'s dolphin',
    'Heermann\'s kangaroo rat',
    'Helan Shan pika',
    'Heller\'s broad-nosed bat',
    'Hellwald\'s spiny rat',
    'Helmeted guineafowl',
    'Herbert\'s rock-wallaby',
    'Herbert River ringtail possum',
    'Hero shrew',
    'Hershkovitz\'s marmoset',
    'Hershkovitz\'s titi',
    'Hewitt\'s red rock hare',
    'Highland cattle',
    'Highland streaked tenrec',
    'Highland yellow-shouldered bat',
    'Highlands punaré',
    'Highveld gerbil',
    'Highveld golden mole',
    'Hildebrandt\'s horseshoe bat',
    'Hildegarde\'s broad-headed mouse',
    'Hildegarde\'s shrew',
    'Hildegarde\'s tomb bat',
    'Hilgendorf\'s tube-nosed bat',
    'Hill\'s roundleaf bat',
    'Hill\'s sheath-tailed bat',
    'Himalayan field rat',
    'Himalayan goral',
    'Himalayan marmot',
    'Himalayan mole',
    'Himalayan serow',
    'Himalayan shrew',
    'Himalayan striped squirrel',
    'Himalayan tahr',
    'Himalayan water shrew',
    'Hippopotamus',
    'Hirola',
    'Hispaniolan greater funnel-eared bat',
    'Hispaniolan hutia',
    'Hispaniolan solenodon',
    'Hispid cotton rat',
    'Hispid hare',
    'Hispid pocket mouse',
    'Hoary bamboo rat',
    'Hoary bat',
    'Hoary fox',
    'Hoary marmot',
    'Hoary wattled bat',
    'Hodgson\'s bat',
    'Hodgson\'s giant flying squirrel',
    'Hoffmann\'s pika',
    'Hoffmann\'s two-toed sloth',
    'Hoffmanns\'s titi',
    'Hog badger',
    'Holland\'s sportive lemur',
    'Honduran white bat',
    'Honey badger',
    'Honey possum',
    'Hooded red-sided opossum',
    'Hooded seal',
    'Hooded skunk',
    'Hopi chipmunk',
    'Horn-skinned bat',
    'Horned lark',
    'Horned puffin',
    'Horse-tailed squirrel',
    'Horsfield\'s bat',
    'Horsfield\'s fruit bat',
    'Horsfield\'s tarsier',
    'Horsfield\'s treeshrew',
    'Hose\'s langur',
    'Hose\'s palm civet',
    'Hottentot golden mole',
    'Hourglass dolphin',
    'House crow',
    'House mouse',
    'House sparrow',
    'Howell\'s forest shrew',
    'Hubbard\'s sportive lemur',
    'Hudsonian godwit',
    'Hugh\'s hedgehog',
    'Humboldt\'s hog-nosed skunk',
    'Humboldt\'s squirrel monkey',
    'Hummelinck\'s vesper mouse',
    'Humpback whale',
    'Hun shrew',
    'Hutan shrew',
    'Hyrax',
    'Iberian lynx',
    'Iberian shrew',
    'Ibex',
    'Ifola tree-kangaroo',
    'Ikonnikov\'s bat',
    'Ili pika',
    'Impala',
    'Incan caenolestid',
    'Incan little mastiff bat',
    'Indian brown mongoose',
    'Indian bush rat',
    'Indian crested porcupine',
    'Indian desert jird',
    'Indian elephant',
    'Indian flying fox',
    'Indian gerbil',
    'Indian giant flying squirrel',
    'Indian giant squirrel',
    'Indian hare',
    'Indian hedgehog',
    'Indian hog deer',
    'Indian leopard',
    'Indian long-eared hedgehog',
    'Indian muntjac',
    'Indian palm squirrel',
    'Indian pangolin',
    'Indian peafowl',
    'Indian pipistrelle',
    'Indian roundleaf bat',
    'Indian spotted chevrotain',
    'Indian star tortoise',
    'Indian wild ass',
    'Indiana bat',
    'Indochinese leopard',
    'Indochinese short-tailed shrew',
    'Indochinese tiger',
    'Indomalayan pencil-tailed tree mouse',
    'Indonesian mountain weasel',
    'Indonesian short-nosed fruit bat',
    'Indri',
    'Inornate squirrel',
    'Insular flying fox',
    'Insular mole',
    'Insular single leaf bat',
    'Insular vole',
    'Intermediate horseshoe bat',
    'Intermediate roundleaf bat',
    'Inyo shrew',
    'Ipanema bat',
    'Iriomote cat',
    'Irrawaddy dolphin',
    'Irrawaddy squirrel',
    'Isabelle\'s ghost bat',
    'Isalo serotine',
    'Island fox',
    'Island mouse',
    'Island tube-nosed fruit bat',
    'Jabiru',
    'Jackass shrew',
    'Jackson\'s mongoose',
    'Jackson\'s shrew',
    'Jaguar',
    'Jaguarundi',
    'Jaliscan cotton rat',
    'Jamaican coney',
    'Jamaican fig-eating bat',
    'Jamaican flower bat',
    'Jamaican fruit bat',
    'Jameson\'s red rock hare',
    'Japanese badger',
    'Japanese dormouse',
    'Japanese dwarf flying squirrel',
    'Japanese giant flying squirrel',
    'Japanese hare',
    'Japanese house bat',
    'Japanese macaque',
    'Japanese marten',
    'Japanese mole',
    'Japanese mountain mole',
    'Japanese serow',
    'Japanese shrew mole',
    'Japanese squirrel',
    'Japanese water shrew',
    'Japanese weasel',
    'Javan ferret-badger',
    'Javan leopard',
    'Javan mongoose',
    'Javan rusa',
    'Javan slit-faced bat',
    'Javan slow loris',
    'Javan surili',
    'Javan tailless fruit bat',
    'Javan warty pig',
    'Javanese flying squirrel',
    'Javanese shrew',
    'Jentink\'s duiker',
    'Johnston\'s forest shrew',
    'Johnston\'s genet',
    'Jolly\'s mouse lemur',
    'Jones\'s roundleaf bat',
    'Jouvenet\'s shrew',
    'Juan Fernández fur seal',
    'Julia Creek dunnart',
    'Juliana\'s golden mole',
    'Jungle cat',
    'Jungle palm squirrel',
    'Junin slender opossum',
    'Kaapori capuchin',
    'Kachin woolly bat',
    'Kahuzi swamp shrew',
    'Kakadu dunnart',
    'Kalahari scrub robin',
    'Kalinowski\'s mastiff bat',
    'Kalinowski\'s mouse opossum',
    'Kamchatka shrew',
    'Kangaroo Island dunnart',
    'Karimi\'s fat-tailed mouse opossum',
    'Kashmir gray langur',
    'Kashmir pygmy shrew',
    'Keast\'s tube-nosed fruit bat',
    'Keen\'s myotis',
    'Kelaart\'s long-clawed shrew',
    'Kelaart\'s pipistrelle',
    'Kelp gull',
    'Kemp\'s gerbil',
    'Kemp\'s thicket rat',
    'Khajuria\'s leaf-nosed bat',
    'Kiang',
    'Kihaule\'s mouse shrew',
    'Kilimanjaro mouse shrew',
    'Kilimanjaro shrew',
    'Killer whale',
    'Kimberley rock monitor',
    'Kimberley rock rat',
    'Kinabalu shrew',
    'Kinda baboon',
    'King colobus',
    'King horseshoe bat',
    'King vulture',
    'Kings\' monitor',
    'Kinkajou',
    'Kipunji',
    'Kirk\'s dik-dik',
    'Kit fox',
    'Kitti\'s hog-nosed bat',
    'Kivu long-haired shrew',
    'Kivu shrew',
    'Klipspringer',
    'Kloss\'s gibbon',
    'Kloss\'s mole',
    'Knob-billed duck',
    'Koala',
    'Kob',
    'Kodkod',
    'Kolar leaf-nosed bat',
    'Kolombatovic\'s long-eared bat',
    'Komodo dragon',
    'Kordofan giraffe',
    'Korean field mouse',
    'Korean hare',
    'Kori bustard',
    'Korrigum',
    'Koslov\'s pika',
    'Kosrae flying fox',
    'Kouprey',
    'Kowari',
    'Kuhl\'s pipistrelle',
    'Kultarr',
    'La Plata dolphin',
    'Lac Alaotra bamboo lemur',
    'Lace monitor',
    'Lacustrine vole',
    'Ladak pika',
    'Lady Burton\'s rope squirrel',
    'Lamia',
    'Lamotte\'s roundleaf bat',
    'Lamotte\'s shrew',
    'Lamulate shrew',
    'Lander\'s horseshoe bat',
    'Laotian langur',
    'Laotian rock rat',
    'Lappet-faced vulture',
    'Lar gibbon',
    'Large-eared free-tailed bat',
    'Large-eared gray shrew',
    'Large-eared horseshoe bat',
    'Large-eared pied bat',
    'Large-eared pika',
    'Large-eared sheath-tailed bat',
    'Large-eared slit-faced bat',
    'Large-eared tenrec',
    'Large-footed bat',
    'Large-headed capuchin',
    'Large-spotted civet',
    'Large-toothed shrew',
    'Large Asian roundleaf bat',
    'Large Indian civet',
    'Large Japanese field mouse',
    'Large bamboo rat',
    'Large flying fox',
    'Large fruit-eating bat',
    'Large mole',
    'Large myotis',
    'Large rufous horseshoe bat',
    'Large slit-faced bat',
    'Large treeshrew',
    'Lasiodora parahybana',
    'Latona\'s shrew',
    'Laughing dove',
    'Laughing kookaburra',
    'Lava gull',
    'Laxmann\'s shrew',
    'Layard\'s palm squirrel',
    'Leach\'s single leaf bat',
    'Leadbeater\'s possum',
    'Least chipmunk',
    'Least dwarf shrew',
    'Least horseshoe bat',
    'Least pipistrelle',
    'Least shrew tenrec',
    'Least weasel',
    'Least yellow bat',
    'Lechwe',
    'Lelwel hartebeest',
    'Lemur-like ringtail possum',
    'Leopard',
    'Leopard cat',
    'Leopard seal',
    'Leschenault\'s rousette',
    'Lesser Asiatic yellow bat',
    'Lesser Congo shrew',
    'Lesser Egyptian jerboa',
    'Lesser Ryukyu shrew',
    'Lesser bamboo bat',
    'Lesser bamboo rat',
    'Lesser bandicoot rat',
    'Lesser brown horseshoe bat',
    'Lesser bulldog bat',
    'Lesser cane rat',
    'Lesser dog-like bat',
    'Lesser dwarf shrew',
    'Lesser false vampire bat',
    'Lesser flamingo',
    'Lesser ghost bat',
    'Lesser gray-brown musk shrew',
    'Lesser great leaf-nosed bat',
    'Lesser grison',
    'Lesser hairy-footed dunnart',
    'Lesser hairy-winged bat',
    'Lesser hedgehog tenrec',
    'Lesser horseshoe bat',
    'Lesser kudu',
    'Lesser large-headed shrew',
    'Lesser long-nosed bat',
    'Lesser long-tailed shrew tenrec',
    'Lesser long-tongued bat',
    'Lesser masked weaver',
    'Lesser mouse-deer',
    'Lesser mouse-eared bat',
    'Lesser mouse-tailed bat',
    'Lesser musky fruit bat',
    'Lesser naked-backed fruit bat',
    'Lesser naked bat',
    'Lesser noctule',
    'Lesser red musk shrew',
    'Lesser ricefield rat',
    'Lesser rock shrew',
    'Lesser sac-winged bat',
    'Lesser sheath-tailed bat',
    'Lesser short-nosed fruit bat',
    'Lesser spear-nosed bat',
    'Lesser spot-nosed monkey',
    'Lesser striped shrew',
    'Lesser tube-nosed bat',
    'Lesser tube-nosed fruit bat',
    'Lesser tufted-tailed rat',
    'Lesser white-toothed shrew',
    'Lesser woolly bat',
    'Lesser woolly horseshoe bat',
    'Lesser yellow-shouldered bat',
    'Levant mole',
    'Liberian mongoose',
    'Lilac-breasted roller',
    'Linnaeus\'s mouse opossum',
    'Linnaeus\'s two-toed sloth',
    'Lion',
    'Lion-tailed macaque',
    'Little Nepalese horseshoe bat',
    'Little bent-wing bat',
    'Little big-eared bat',
    'Little big-eyed bat',
    'Little black serotine',
    'Little broad-nosed bat',
    'Little brown bat',
    'Little collared fruit bat',
    'Little cormorant',
    'Little forest bat',
    'Little free-tailed bat',
    'Little goblin bat',
    'Little golden-mantled flying fox',
    'Little grebe',
    'Little ground squirrel',
    'Little long-tailed dunnart',
    'Little native mouse',
    'Little penguin',
    'Little pocket mouse',
    'Little red brocket',
    'Little red flying fox',
    'Little red kaluta',
    'Little white-shouldered bat',
    'Little woolly mouse opossum',
    'Little yellow-shouldered bat',
    'Little yellow bat',
    'Livingstone\'s fruit bat',
    'Llama',
    'Llanos long-nosed armadillo',
    'Lodgepole chipmunk',
    'Long-billed corella',
    'Long-clawed shrew',
    'Long-crested eagle',
    'Long-eared chipmunk',
    'Long-eared flying mouse',
    'Long-eared hedgehog',
    'Long-eared jerboa',
    'Long-eared myotis',
    'Long-fingered bat',
    'Long-fingered triok',
    'Long-finned pilot whale',
    'Long-footed potoroo',
    'Long-footed rat',
    'Long-footed shrew',
    'Long-footed treeshrew',
    'Long-footed water rat',
    'Long-haired rat',
    'Long-haired rousette',
    'Long-legged bat',
    'Long-legged myotis',
    'Long-nosed bandicoot',
    'Long-nosed caenolestid',
    'Long-nosed dasyure',
    'Long-nosed echymipera',
    'Long-nosed hocicudo',
    'Long-nosed mole',
    'Long-nosed mongoose',
    'Long-nosed potoroo',
    'Long-nosed short-tailed opossum',
    'Long-snouted bat',
    'Long-tailed brown-toothed shrew',
    'Long-tailed chinchilla',
    'Long-tailed dunnart',
    'Long-tailed forest shrew',
    'Long-tailed fruit bat',
    'Long-tailed giant rat',
    'Long-tailed goral',
    'Long-tailed ground squirrel',
    'Long-tailed jaeger',
    'Long-tailed marmot',
    'Long-tailed mole',
    'Long-tailed mountain shrew',
    'Long-tailed musk shrew',
    'Long-tailed planigale',
    'Long-tailed pocket mouse',
    'Long-tailed porcupine',
    'Long-tailed pygmy possum',
    'Long-tailed shrew',
    'Long-tailed spiny rat',
    'Long-tailed vole',
    'Long-tailed weasel',
    'Long-tongued fruit bat',
    'Long-tongued nectar bat',
    'Long-winged tomb bat',
    'Lord Derby\'s scaly-tailed squirrel',
    'Lord Howe long-eared bat',
    'Loring\'s rat',
    'Louis\'s yellow-shouldered bat',
    'Lovat\'s climbing mouse',
    'Low\'s squirrel',
    'Lowe\'s mona monkey',
    'Lowe\'s shrew',
    'Lowland brush mouse',
    'Lowland paca',
    'Lowland ringtail possum',
    'Lowland streaked tenrec',
    'Lowlands tree-kangaroo',
    'Lucifer titi',
    'Lucina\'s shrew',
    'Ludia\'s shrew',
    'Luis Manuel\'s tailless bat',
    'Lumholtz\'s tree-kangaroo',
    'Lusitanian pine vole',
    'Lutrine opossum',
    'Luzon fruit bat',
    'Luzon hairy-tailed rat',
    'Luzon montane forest mouse',
    'Luzon shrew',
    'Luzon striped rat',
    'Lyle\'s flying fox',
    'MacArthur\'s mouse lemur',
    'MacArthur\'s shrew',
    'MacConnell\'s bat',
    'MacMillan\'s shrew',
    'Maclaud\'s horseshoe bat',
    'Macleay\'s dorcopsis',
    'Macleay\'s mustached bat',
    'Madagascan flying fox',
    'Madagascan fruit bat',
    'Madagascan pygmy shrew',
    'Madagascan rousette',
    'Madagascar free-tailed bat',
    'Madagascar sucker-footed bat',
    'Madame Berthe\'s mouse lemur',
    'Madeira pipistrelle',
    'Madidi titi',
    'Madras treeshrew',
    'Madura horseshoe bat',
    'Maduran leaf-nosed bat',
    'Magellanic penguin',
    'Magellanic tuco-tuco',
    'Maggie Taylor\'s roundleaf bat',
    'Maghreb garden dormouse',
    'Magnificent frigatebird',
    'Mahogany glider',
    'Mainland serow',
    'Major\'s long-fingered bat',
    'Major\'s long-tailed tenrec',
    'Major\'s tufted-tailed rat',
    'Makira flying fox',
    'Makira roundleaf bat',
    'Makwassie musk shrew',
    'Malabar large-spotted civet ',
    'Malabar spiny dormouse',
    'Malachite kingfisher',
    'Malagasy civet',
    'Malagasy giant rat',
    'Malagasy mountain mouse',
    'Malagasy mouse-eared bat',
    'Malagasy serotine',
    'Malagasy white-bellied free-tailed bat',
    'Malayan civet',
    'Malayan horseshoe bat',
    'Malayan porcupine',
    'Malayan pygmy shrew',
    'Malayan shrew',
    'Malayan tailless leaf-nosed bat',
    'Malayan tiger',
    'Malayan water shrew',
    'Malayan weasel',
    'Malbrouck',
    'Mallard',
    'Malleefowl',
    'Maluku myotis',
    'Mamore arboreal rice rat',
    'Manado fruit bat',
    'Manatee',
    'Manchurian hare',
    'Mandarin vole',
    'Mandrill',
    'Maned rat',
    'Maned sloth',
    'Maned wolf',
    'Manenguba shrew',
    'Mangrove monitor',
    'Manipur bush rat',
    'Mantled guereza',
    'Mantled howler',
    'Manu short-tailed bat',
    'Marabou stork',
    'Maranhão red-handed howler',
    'Marbled cat',
    'Marbled polecat',
    'Mareeba rock-wallaby',
    'Margay',
    'Margot Marsh\'s mouse lemur',
    'Mariana fruit bat',
    'Marine iguana',
    'Marine otter',
    'Marinkelle\'s sword-nosed bat',
    'Maritime shrew',
    'Maritime striped squirrel',
    'Markhor',
    'Marley\'s golden mole',
    'Marohita mouse lemur',
    'Maroon leaf monkey',
    'Marovaza house bat',
    'Marsh deer',
    'Marsh mongoose',
    'Marsh rabbit',
    'Marsh rice rat',
    'Marsh shrew',
    'Marshall\'s horseshoe bat',
    'Martins\'s tamarin',
    'Masai giraffe',
    'Mashona mole-rat',
    'Masked booby',
    'Masked flying fox',
    'Masked palm civet',
    'Masked ringtail possum',
    'Masoala fork-marked lemur',
    'Matapalo broad-nosed bat',
    'Mato Grosso dog-faced bat',
    'Matschie\'s tree-kangaroo',
    'Matthey\'s mouse',
    'Mauritanian shrew',
    'Mauritian flying fox',
    'Mauritian tomb bat',
    'Maués marmoset',
    'Maxwell\'s duiker',
    'Mazama pocket gopher',
    'McIlhenny\'s four-eyed opossum',
    'Meadow jumping mouse',
    'Meadow vole',
    'Mearns\'s squirrel',
    'Medellín small-eared shrew',
    'Mediterranean horseshoe bat',
    'Mediterranean monk seal',
    'Mediterranean water shrew',
    'Meerkat',
    'Mehely\'s horseshoe bat',
    'Melissa\'s yellow-eared bat',
    'Meller\'s mongoose',
    'Melon-headed whale',
    'Mentawai langur',
    'Menzbier\'s marmot',
    'Merida small-eared shrew',
    'Meridional serotine',
    'Merriam\'s chipmunk',
    'Merriam\'s kangaroo rat',
    'Merriam\'s pocket gopher',
    'Merriam\'s shrew',
    'Mertens\' water monitor',
    'Mexican agouti',
    'Mexican beaded lizard',
    'Mexican big-eared bat',
    'Mexican cottontail',
    'Mexican dog-faced bat',
    'Mexican fox squirrel',
    'Mexican free-tailed bat',
    'Mexican funnel-eared bat',
    'Mexican gray squirrel',
    'Mexican greater funnel-eared bat',
    'Mexican ground squirrel',
    'Mexican hairy dwarf porcupine',
    'Mexican howler',
    'Mexican long-tailed shrew',
    'Mexican long-tongued bat',
    'Mexican mouse opossum',
    'Mexican prairie dog',
    'Mexican shrew',
    'Mexican small-eared shrew',
    'Mexican spider monkey',
    'Mexican spiny pocket mouse',
    'Mexican vole',
    'Mexican wolf',
    'Mexican woodrat',
    'Michoacan deer mouse',
    'Midas free-tailed bat',
    'Midday jird',
    'Miller\'s mastiff bat',
    'Milne-Edwards\' sportive lemur',
    'Mindanao hairy-tailed rat',
    'Mindanao mountain rat',
    'Mindanao pygmy fruit bat',
    'Mindanao shrew',
    'Mindanao treeshrew',
    'Minor epauletted fruit bat',
    'Minute fruit bat',
    'Miss Waldron\'s red colobus',
    'Mitchell\'s hopping mouse',
    'Mitchell\'s water monitor',
    'Mittermeier\'s mouse lemur',
    'Mittermeier\'s sportive lemur',
    'Mocking cliff chat',
    'Mohave ground squirrel',
    'Mohol bushbaby',
    'Mole-like rice tenrec',
    'Molina\'s hog-nosed skunk',
    'Moloney\'s mimic bat',
    'Moluccan flying fox',
    'Mona monkey',
    'Mondolfi\'s four-eyed opossum',
    'Mongalla free-tailed bat',
    'Mongalla gazelle',
    'Mongolian five-toed jerboa',
    'Mongolian gazelle',
    'Mongolian gerbil',
    'Mongolian wild ass',
    'Mongoose lemur',
    'Monito del monte',
    'Monjon',
    'Montane guinea pig',
    'Montane monkey-faced bat',
    'Montane mouse shrew',
    'Montane myotis',
    'Montane shrew',
    'Montane shrew tenrec',
    'Montane vole',
    'Montane water vole',
    'Montane white-toothed shrew',
    'Moojen\'s Atlantic spiny rat',
    'Moon forest shrew',
    'Moonrat',
    'Moonshine shrew',
    'Moor macaque',
    'Moore\'s woolly lemur',
    'Moose',
    'Morelia spilota',
    'Moss-forest blossom bat',
    'Mottle-faced tamarin',
    'Mouflon',
    'Mount Cameroon forest shrew',
    'Mount Claro rock-wallaby',
    'Mount Kenya mole shrew',
    'Mount Lyell shrew',
    'Mountain beaver',
    'Mountain brushtail possum',
    'Mountain cottontail',
    'Mountain cuscus',
    'Mountain degu',
    'Mountain gazelle',
    'Mountain giant Sunda rat',
    'Mountain goat',
    'Mountain gorilla',
    'Mountain ground squirrel',
    'Mountain hare',
    'Mountain nyala',
    'Mountain paca',
    'Mountain pademelon',
    'Mountain pocket gopher',
    'Mountain pygmy possum',
    'Mountain reedbuck',
    'Mountain treeshrew',
    'Mountain tube-nosed fruit bat',
    'Mountain weasel',
    'Moupin pika',
    'Mourning collared dove',
    'Moustached guenon',
    'Moustached tamarin',
    'Muennink\'s spiny rat',
    'Mule deer',
    'Muskox',
    'Muskrat',
    'Musky rat-kangaroo',
    'Mutable sun squirrel',
    'Myanmar snub-nosed monkey',
    'Myotis macropus',
    'Mzab gundi',
    'Müller\'s giant Sunda rat',
    'Nabarlek',
    'Naked-nosed shrew tenrec',
    'Naked-rumped pouched bat',
    'Naked-rumped tomb bat',
    'Naked mole-rat',
    'Namaqua dune mole-rat',
    'Namaqua rock rat',
    'Namdapha flying squirrel',
    'Nancy Ma\'s night monkey',
    'Napo spiny rat',
    'Narrow-faced kangaroo rat',
    'Narrow-headed vole',
    'Narrow-nosed planigale',
    'Narrow-striped marsupial shrew',
    'Narrow-striped mongoose',
    'Narrow-winged pipistrelle',
    'Nasolo\'s shrew tenrec',
    'Natal free-tailed bat',
    'Natal multimammate mouse',
    'Natal red rock hare',
    'Nathusius\'s pipistrelle',
    'Natterer\'s bat',
    'Natuna Island surili',
    'Neblina slender opossum',
    'Neblina uakari',
    'Necklace pipistrelle',
    'Negev shrew',
    'Negros shrew',
    'Nelson\'s collared lemming',
    'Nelson\'s pocket mouse',
    'Nelson\'s small-eared shrew',
    'Nelson\'s spiny pocket mouse',
    'Neotropic cormorant',
    'Neotropical otter',
    'Nepal gray langur',
    'Nepal myotis',
    'Neumann\'s grass rat',
    'New Britain naked-backed fruit bat',
    'New Caledonia blossom bat',
    'New Caledonia flying fox',
    'New England cottontail',
    'New Georgian monkey-faced bat',
    'New Guinea big-eared bat',
    'New Guinea long-eared bat',
    'New Guinea waterside rat',
    'New Guinean planigale',
    'New Guinean quoll',
    'New Holland mouse',
    'New Zealand greater short-tailed bat',
    'New Zealand lesser short-tailed bat',
    'New Zealand long-tailed bat',
    'New Zealand sea lion',
    'Nicaraguan spider monkey',
    'Niceforo\'s big-eared bat',
    'Nicobar flying fox',
    'Nicobar long-tailed macaque',
    'Nicobar shrew',
    'Nicobar treeshrew',
    'Niger Delta red colobus',
    'Nigerian free-tailed bat',
    'Nigerian shrew',
    'Nile crocodile',
    'Nile lechwe',
    'Nilgai',
    'Nilgiri langur',
    'Nilgiri long-tailed tree mouse',
    'Nilgiri marten',
    'Nilgiri tahr',
    'Nimba otter shrew',
    'Nimba shrew',
    'Nine-banded armadillo',
    'Ningbing false antechinus',
    'Niobe\'s shrew',
    'Noack\'s roundleaf bat',
    'Nolthenius\'s long-tailed climbing mouse',
    'North African elephant shrew',
    'North African gerbil',
    'North African hedgehog',
    'North African white-toothed shrew',
    'North American beaver',
    'North American brown lemming',
    'North American least shrew',
    'North American porcupine',
    'North American river otter',
    'North Atlantic right whale',
    'North Pacific right whale',
    'North Sulawesi babirusa',
    'Northern Amazon red squirrel',
    'Northern Luzon giant cloud rat',
    'Northern bat',
    'Northern bettong',
    'Northern birch mouse',
    'Northern bog lemming',
    'Northern broad-nosed bat',
    'Northern brown bandicoot',
    'Northern brown howler',
    'Northern caenolestid',
    'Northern carmine bee-eater',
    'Northern collared lemming',
    'Northern common cuscus',
    'Northern elephant seal',
    'Northern flying squirrel',
    'Northern free-tailed bat',
    'Northern fur seal',
    'Northern ghost bat',
    'Northern giant mouse lemur',
    'Northern giraffe',
    'Northern glider',
    'Northern gracile opossum',
    'Northern grasshopper mouse',
    'Northern greater galago',
    'Northern hairy-nosed wombat',
    'Northern leaf-nosed bat',
    'Northern little yellow-eared bat',
    'Northern marsupial mole',
    'Northern mole vole',
    'Northern muriqui',
    'Northern nail-tail wallaby',
    'Northern needle-clawed bushbaby',
    'Northern olingo',
    'Northern palm squirrel',
    'Northern pig-tailed macaque',
    'Northern pika',
    'Northern pipistrelle',
    'Northern plains gray langur',
    'Northern pocket gopher',
    'Northern quoll',
    'Northern red-backed vole',
    'Northern red-sided opossum',
    'Northern right whale dolphin',
    'Northern rufous mouse lemur',
    'Northern short-tailed shrew',
    'Northern shrew tenrec',
    'Northern smooth-tailed treeshrew',
    'Northern sportive lemur',
    'Northern tamandua',
    'Northern three-striped opossum',
    'Northern three-toed jerboa',
    'Northern treeshrew',
    'Northern water rat',
    'Northern white-breasted hedgehog',
    'Northern white-cheeked gibbon',
    'Northern yellow bat',
    'Northwest African cheetah',
    'Northwestern deer mouse',
    'Norway lemming',
    'Nubian giraffe',
    'Nubian ibex',
    'Nubra pika',
    'Numbat',
    'Nusatenggara short-nosed fruit bat',
    'Nyala',
    'Ocelot',
    'Ogilby\'s duiker',
    'Ogilvie Mountains collared lemming',
    'Okapi',
    'Oku mouse shrew',
    'Oldfield mouse',
    'Olinguito',
    'Olive-backed pocket mouse',
    'Olive baboon',
    'Olive colobus',
    'Olympic marmot',
    'Olympic shrew',
    'Omilteme cottontail',
    'Onager',
    'Oncilla',
    'One-striped opossum',
    'Ooldea dunnart',
    'Openbill stork',
    'Orange-bellied Himalayan squirrel',
    'Orange leaf-nosed bat',
    'Orange nectar bat',
    'Orbiculus leaf-nosed bat',
    'Ord\'s kangaroo rat',
    'Oribi',
    'Oriental shrew',
    'Orinoco sword-nosed bat',
    'Orizaba long-tailed shrew',
    'Ornate cuscus',
    'Ornate flying fox',
    'Ornate shrew',
    'Ornate spider monkey',
    'Ornate titi',
    'Osgood\'s short-tailed opossum',
    'Osprey',
    'Ostrich',
    'Otter civet',
    'Otto\'s sportive lemur',
    'Ovenbird',
    'Owston\'s palm civet',
    'Oxybelis fulgidus',
    'Paca',
    'Pacarana',
    'Pacific gull',
    'Pacific jumping mouse',
    'Pacific sheath-tailed bat',
    'Pacific shrew',
    'Pacific white-sided dolphin',
    'Pagai Island macaque',
    'Painted bat',
    'Painted big-eared mouse',
    'Painted ringtail possum',
    'Painted stork',
    'Painted tree-rat',
    'Painted treeshrew',
    'Palawan bearded pig',
    'Palawan flying squirrel',
    'Palawan fruit bat',
    'Palawan shrew',
    'Palawan stink badger',
    'Palawan treeshrew',
    'Pale-faced bat',
    'Pale-throated sloth',
    'Pale fork-marked lemur',
    'Pale fox',
    'Pale gerbil',
    'Pale kangaroo mouse',
    'Pale shrew tenrec',
    'Pale spear-nosed bat',
    'Pale white-eye',
    'Pallas\'s cat',
    'Pallas\'s fish eagle',
    'Pallas\'s long-tongued bat',
    'Pallas\'s pika',
    'Pallas\'s squirrel',
    'Pallas\'s tube-nosed bat',
    'Pallid bat',
    'Pallid large-footed myotis',
    'Palmer\'s chipmunk',
    'Pampas deer',
    'Pampas fox',
    'Panama slender opossum',
    'Panamanian spiny pocket mouse',
    'Panamint kangaroo rat',
    'Panay cloudrunner',
    'Panniet naked-backed fruit bat',
    'Pantropical spotted dolphin',
    'Papilio canadensis',
    'Papillose woolly bat',
    'Papuan bandicoot',
    'Paraguaian hairy dwarf porcupine',
    'Paraguayan fat-tailed mouse opossum',
    'Paraguayan punaré',
    'Pardine genet',
    'Pariente\'s fork-marked lemur',
    'Parma wallaby',
    'Parnell\'s mustached bat',
    'Parti-coloured bat',
    'Particolored flying squirrel',
    'Patagonian bonneted bat',
    'Patagonian mara',
    'Patagonian opossum',
    'Patagonian weasel',
    'Patas monkey',
    'Patrizi\'s trident leaf-nosed bat',
    'Paucident planigale',
    'Peale\'s free-tailed bat',
    'Pearson\'s horseshoe bat',
    'Pearson\'s long-clawed shrew',
    'Pearson\'s tuco-tuco',
    'Pel\'s pouched bat',
    'Peleng leaf-nosed bat',
    'Peleng tarsier',
    'Pelew flying fox',
    'Pemba flying fox',
    'Pen-tailed treeshrew',
    'Peninsular horseshoe bat',
    'Peninsular myotis',
    'Peninsular shrew',
    'Pennant\'s colobus',
    'Percival\'s spiny mouse',
    'Percival\'s trident bat',
    'Peregrine falcon',
    'Perentie',
    'Perny\'s long-nosed squirrel',
    'Perrier\'s sifaka',
    'Persian fallow deer',
    'Persian jird',
    'Peruvian night monkey',
    'Peruvian spider monkey',
    'Peters\'s duiker',
    'Peters\'s epauletted fruit bat',
    'Peters\'s flat-headed bat',
    'Peters\'s fruit bat',
    'Peters\'s squirrel',
    'Peters\'s trumpet-eared bat',
    'Petter\'s sportive lemur',
    'Phayre\'s leaf monkey',
    'Phayre\'s squirrel',
    'Philippine dawn bat',
    'Philippine deer',
    'Philippine flying lemur',
    'Philippine forest horseshoe bat',
    'Philippine forest roundleaf bat',
    'Philippine long-tailed macaque',
    'Philippine mouse-deer',
    'Philippine naked-backed fruit bat',
    'Philippine pangolin',
    'Philippine porcupine',
    'Philippine pygmy roundleaf bat',
    'Philippine slow loris',
    'Philippine swamphen',
    'Philippine tarsier',
    'Philippine tree squirrel',
    'Philippine tube-nosed fruit bat',
    'Philippine warty pig',
    'Phou Khao Khouay leaf-nosed bat',
    'Pichi',
    'Piebald shrew',
    'Pied avocet',
    'Pied bat',
    'Pied butcherbird',
    'Pied crow',
    'Pied kingfisher',
    'Pied tamarin',
    'Pig-tailed langur',
    'Pilbara ningaui',
    'Pileated gibbon',
    'Pine siskin',
    'Pine squirrel',
    'Pinheiro\'s slender opossum',
    'Pinyon mouse',
    'Piute ground squirrel',
    'Plains pocket gopher',
    'Plains pocket mouse',
    'Plains rat',
    'Plains viscacha',
    'Plains viscacha rat',
    'Plains zebra',
    'Plantain squirrel',
    'Plateau pika',
    'Plateau vole',
    'Platypus',
    'Platyrrhinus albericoi',
    'Platyrrhinus ismaeli',
    'Plush-coated ringtail possum',
    'Pocketed free-tailed bat',
    'Pogona minor',
    'Pohle\'s fruit bat',
    'Polar bear',
    'Polynesian rat',
    'Pomona roundleaf bat',
    'Pond bat',
    'Potoroo',
    'Potto',
    'Prairie falcon',
    'Prairie shrew',
    'Prairie vole',
    'Pratt\'s roundleaf bat',
    'Preble\'s shrew',
    'Prehensile-tailed hutia',
    'Preuss\'s monkey',
    'Preuss\'s red colobus',
    'Prevost\'s squirrel',
    'Pribilof Island shrew',
    'Prince Bernhard\'s titi',
    'Prince Demidoff\'s bushbaby',
    'Proboscis bat',
    'Proboscis monkey',
    'Pronghorn',
    'Proserpine rock-wallaby',
    'Przewalski\'s gazelle',
    'Przewalski\'s steppe lemming',
    'Puku',
    'Puna ibis',
    'Purple-crested turaco',
    'Purple-faced langur',
    'Purple-necked rock-wallaby',
    'Purple grenadier',
    'Pygmy brocket',
    'Pygmy fruit-eating bat',
    'Pygmy fruit bat',
    'Pygmy hippopotamus',
    'Pygmy hog',
    'Pygmy long-eared bat',
    'Pygmy marmoset',
    'Pygmy mouse lemur',
    'Pygmy mulga monitor',
    'Pygmy possum',
    'Pygmy rabbit',
    'Pygmy ringtail possum',
    'Pygmy round-eared bat',
    'Pygmy scaly-tailed flying squirrel',
    'Pygmy short-tailed opossum',
    'Pygmy shrew tenrec',
    'Pygmy slow loris',
    'Pygmy spotted skunk',
    'Pygmy three-toed sloth',
    'Pygmy treeshrew',
    'Pyrenean chamois',
    'Pyrenean desman',
    'Père David\'s rock squirrel',
    'Quechuan mouse opossum',
    'Quokka',
    'Raccoon',
    'Raccoon dog',
    'Radde\'s shrew',
    'Radiated tortoise',
    'Raffles\' banded langur',
    'Raffray\'s bandicoot',
    'Raffray\'s sheath-tailed bat',
    'Rafinesque\'s big-eared bat',
    'Railer bat',
    'Rainbow lorikeet',
    'Rakali',
    'Ramanantsoavana\'s woolly lemur',
    'Randrianasolo\'s sportive lemur',
    'Ratanaworabhan\'s fruit bat',
    'Recife broad-nosed bat',
    'Reclusive ringtail possum',
    'Red-and-green macaw',
    'Red-backed bearded saki',
    'Red-bellied lemur',
    'Red-bellied marsupial shrew',
    'Red-bellied titi',
    'Red-billed buffalo weaver',
    'Red-billed hornbill',
    'Red-billed tropicbird',
    'Red-breasted nuthatch',
    'Red-capped cardinal',
    'Red-cheeked cordon-bleu',
    'Red-cheeked dunnart',
    'Red-cheeked ground squirrel',
    'Red-eared guenon',
    'Red-faced spider monkey',
    'Red-fan parrot',
    'Red-flanked duiker',
    'Red-fronted gazelle',
    'Red-fronted lemur',
    'Red-handed howler',
    'Red-handed tamarin',
    'Red-headed titi',
    'Red-headed woodpecker',
    'Red-hipped squirrel',
    'Red-knobbed coot',
    'Red-legged pademelon',
    'Red-legged sun squirrel',
    'Red-necked pademelon',
    'Red-necked phalarope',
    'Red-necked wallaby',
    'Red-rumped agouti',
    'Red-shanked douc',
    'Red-tailed black cockatoo',
    'Red-tailed chipmunk',
    'Red-tailed hawk',
    'Red-tailed monkey',
    'Red-tailed phascogale',
    'Red-tailed sportive lemur',
    'Red-tailed squirrel',
    'Red-winged blackbird',
    'Red acouchi',
    'Red and white giant flying squirrel',
    'Red brocket',
    'Red bush squirrel',
    'Red climbing mouse',
    'Red deer',
    'Red forest duiker',
    'Red fox',
    'Red giant flying squirrel',
    'Red goral',
    'Red hartebeest',
    'Red kangaroo',
    'Red lemur',
    'Red myotis',
    'Red panda',
    'Red phalarope',
    'Red river hog',
    'Red rock rat',
    'Red ruffed lemur',
    'Red serow',
    'Red slender loris',
    'Red spiny rat',
    'Red squirrel',
    'Red tree vole',
    'Red wolf',
    'Reddish-gray mouse lemur',
    'Reddish-gray musk shrew',
    'Reed vole',
    'Reeves\'s muntjac',
    'Reig\'s opossum',
    'Reig\'s tuco-tuco',
    'Reindeer',
    'Remy\'s pygmy shrew',
    'Rendall\'s serotine',
    'Rennell flying fox',
    'Reticulated giraffe',
    'Rhesus macaque',
    'Rhim gazelle',
    'Ribbon seal',
    'Ricefield rat',
    'Richardson\'s collared lemming',
    'Richardson\'s ground squirrel',
    'Richmond\'s squirrel',
    'Rickett\'s big-footed bat',
    'Ridley\'s bat',
    'Ridley\'s leaf-nosed bat',
    'Ring-tailed cat',
    'Ring-tailed lemur',
    'Ringed seal',
    'Rio Beni titi',
    'Rio Mayo titi',
    'Rio Purus titi',
    'Riparian myotis',
    'Risso\'s dolphin',
    'Riverine rabbit',
    'Roach\'s mouse-tailed dormouse',
    'Roan antelope',
    'Roberto\'s spiny rat',
    'Robinson\'s banded langur',
    'Robinson\'s mouse opossum',
    'Robust cottontail',
    'Robust golden mole',
    'Robust yellow bat',
    'Rock-haunting ringtail possum',
    'Rock cavy',
    'Rock dove',
    'Rock hyrax',
    'Rock pocket mouse',
    'Rock squirrel',
    'Rock vole',
    'Rodrigues flying fox',
    'Roe deer',
    'Rohu\'s bat',
    'Roloway monkey',
    'Roman mole',
    'Ronald\'s opossum',
    'Rondo dwarf galago',
    'Rondon\'s marmoset',
    'Roosevelt\'s shrew',
    'Rory Cooper\'s false antechinus',
    'Rose-ringed parakeet',
    'Rosenberg\'s monitor',
    'Ross seal',
    'Rothschild\'s cuscus',
    'Rothschild\'s porcupine',
    'Rothschild\'s rock-wallaby',
    'Rough-haired golden mole',
    'Rough-toothed dolphin',
    'Round-eared tube-nosed bat',
    'Round-tailed ground squirrel',
    'Round-tailed muskrat',
    'Royal antelope',
    'Royal tern',
    'Royle\'s pika',
    'Ruatan Island agouti',
    'Rudd\'s mouse',
    'Ruddy mongoose',
    'Ruddy treeshrew',
    'Rufous-collared sparrow',
    'Rufous elephant shrew',
    'Rufous hare-wallaby',
    'Rufous horseshoe bat',
    'Rufous mouse-eared bat',
    'Rufous mouse opossum',
    'Rufous rat-kangaroo',
    'Rufous soft-furred spiny rat',
    'Rufous treepie',
    'Rufous trident bat',
    'Rumpi mouse shrew',
    'Russet ground squirrel',
    'Russian desman',
    'Rusty-bellied brush-furred rat',
    'Rusty-spotted cat',
    'Rusty-spotted genet',
    'Ruwenzori horseshoe bat',
    'Ruwenzori otter shrew',
    'Ruwenzori shrew',
    'Ryukyu flying fox',
    'Ryukyu long-tailed giant rat',
    'Ryukyu shrew',
    'Ryukyu spiny rat',
    'Rüppell\'s broad-nosed bat',
    'Rüppell\'s fox',
    'Rüppell\'s horseshoe bat',
    'Rüppell\'s pipistrelle',
    'Sable',
    'Sable antelope',
    'Saddle-billed stork',
    'Sado mole',
    'Sagebrush vole',
    'Sahamalaza sportive lemur',
    'Saharan striped polecat',
    'Sahelian tiny shrew',
    'Sahyadris forest rat',
    'Saiga antelope',
    'Saimaa ringed seal',
    'Saint Lawrence Island shrew',
    'Salim Ali\'s fruit bat',
    'Salt\'s dik-dik',
    'Salt marsh harvest mouse',
    'Salvadora hexalepis',
    'Salvin\'s big-eyed bat',
    'Sambar deer',
    'Sambirano mouse lemur',
    'Sambirano woolly lemur',
    'Samoa flying fox',
    'San Cristobal shrew',
    'San Diego pocket mouse',
    'San Felipe hutia',
    'San Joaquin antelope squirrel',
    'San Quintin kangaroo rat',
    'Sanborn\'s bonneted bat',
    'Sand-colored soft-furred rat',
    'Sand cat',
    'Sand goanna',
    'Sandhill crane',
    'Sandhill dunnart',
    'Sandstone false antechinus',
    'Sandy inland mouse',
    'Sandy mole-rat',
    'Sanford\'s brown lemur',
    'Sanghir squirrel',
    'Sangihe tarsier',
    'Sanje mangabey',
    'Santa Catarina\'s guinea pig',
    'Santa Marta porcupine',
    'Santa Marta white-fronted capuchin',
    'Saola',
    'Sarawak surili',
    'Sardinian long-eared bat',
    'Sarus crane',
    'Satéré marmoset',
    'Saussure\'s shrew',
    'Savanna dwarf shrew',
    'Savanna path shrew',
    'Savanna shrew',
    'Savi\'s pine vole',
    'Savi\'s pipistrelle',
    'Scaly-breasted lorikeet',
    'Scaly-footed small-eared shrew',
    'Scaly-tailed possum',
    'Scarlet macaw',
    'Sceloporus magister',
    'Schlieffen\'s bat',
    'Schmidts\'s big-eared bat',
    'Schneider\'s leaf-nosed bat',
    'Schreber\'s yellow bat',
    'Schultz\'s round-eared bat',
    'Schwartz\'s myotis',
    'Sclater\'s golden mole',
    'Sclater\'s guenon',
    'Sclater\'s mouse shrew',
    'Sclater\'s shrew',
    'Scott\'s sportive lemur',
    'Screaming hairy armadillo',
    'Scrub hare',
    'Sea otter',
    'Seal\'s sportive lemur',
    'Seba\'s short-tailed bat',
    'Sechuran fox',
    'Secretarybird',
    'Sei whale',
    'Seminole bat',
    'Senegal bushbaby',
    'Senkaku mole',
    'Sepia short-tailed opossum',
    'Seram bandicoot',
    'Seri\'s sheath-tailed bat',
    'Seri\'s tree-kangaroo',
    'Serotine bat',
    'Serval',
    'Servaline genet',
    'Seurat\'s spiny mouse',
    'Seven-banded armadillo',
    'Seychelles fruit bat',
    'Seychelles sheath-tailed bat',
    'Shaggy bat',
    'Shamel\'s horseshoe bat',
    'Sharpe\'s grysbok',
    'Shaw\'s jird',
    'Shield-faced roundleaf bat',
    'Shinto shrew',
    'Shock-headed capuchin',
    'Short-beaked common dolphin',
    'Short-beaked echidna',
    'Short-eared bat',
    'Short-eared dog',
    'Short-eared possum',
    'Short-eared rock-wallaby',
    'Short-faced mole',
    'Short-furred dasyure',
    'Short-headed broad-nosed bat',
    'Short-nosed bandicoot',
    'Short-palated fruit bat',
    'Short-snouted elephant shrew',
    'Short-tailed bandicoot rat',
    'Short-tailed chinchilla',
    'Short-tailed gymnure',
    'Short-tailed mongoose',
    'Short-tailed roundleaf bat',
    'Short-tailed shrew tenrec',
    'Shortridge\'s horseshoe bat',
    'Shortridge\'s langur',
    'Shrew-faced squirrel',
    'Shrew-toothed shrew tenrec',
    'Shrew gymnure',
    'Siamang',
    'Siau Island tarsier',
    'Siberian brown lemming',
    'Siberian chipmunk',
    'Siberian flying squirrel',
    'Siberian ibex',
    'Siberian large-toothed shrew',
    'Siberian musk deer',
    'Siberian roe deer',
    'Siberian shrew',
    'Siberian tiger',
    'Siberian weasel',
    'Siberian zokor',
    'Siberut macaque',
    'Sibree\'s dwarf lemur',
    'Sicilian shrew',
    'Side-striped jackal',
    'Sierra Leone free-tailed bat',
    'Sierra Madre ground squirrel',
    'Sika deer',
    'Silky anteater',
    'Silky cuscus',
    'Silky pocket mouse',
    'Silky short-tailed bat',
    'Silky sifaka',
    'Silver-haired bat',
    'Silver-tipped myotis',
    'Silver fruit-eating bat',
    'Silver gull',
    'Silver mountain vole',
    'Silvered bat',
    'Silvery gibbon',
    'Silvery greater galago',
    'Silvery lutung',
    'Silvery marmoset',
    'Silvery mole-rat',
    'Silvery woolly monkey',
    'Simmons\' mouse lemur',
    'Sinaloan mastiff bat',
    'Sinaloan pocket mouse',
    'Singing vole',
    'Single-striped grass mouse',
    'Sitatunga',
    'Six-banded armadillo',
    'Slender-tailed dunnart',
    'Slender loris',
    'Slender mongoose',
    'Slender shrew',
    'Slender squirrel',
    'Slender treeshrew',
    'Slender yellow bat',
    'Sloggett\'s vlei rat',
    'Sloth bear',
    'Small-footed shrew',
    'Small-toothed fruit bat',
    'Small-toothed palm civet',
    'Small-toothed sportive lemur',
    'Small Asian sheath-tailed bat',
    'Small Indian civet',
    'Small Japanese field mouse',
    'Small Japanese mole',
    'Small big-eared brown bat',
    'Small dorcopsis',
    'Small five-toed jerboa',
    'Small flying fox',
    'Small mouse-tailed bat',
    'Small red brocket',
    'Small vesper mouse',
    'Small woolly bat',
    'Smaller horseshoe bat',
    'Smith\'s bush squirrel',
    'Smith\'s red rock hare',
    'Smith\'s shrew',
    'Smoky bat',
    'Smoky flying squirrel',
    'Smoky shrew',
    'Smoky white-toothed shrew',
    'Smooth-coated otter',
    'Snow goose',
    'Snow leopard',
    'Snow sheep',
    'Snowshoe hare',
    'Snowy egret',
    'Snowy owl',
    'Snowy sheathbill',
    'Sociable weaver',
    'Social pipistrelle',
    'Social vole',
    'Sockeye salmon',
    'Sody\'s tree rat',
    'Sody\'s yellow house bat',
    'Soemmerring\'s gazelle',
    'Soft-spined Atlantic spiny rat',
    'Solomon\'s naked-backed fruit bat',
    'Solomons flying fox',
    'Somali bushbaby',
    'Somali dwarf shrew',
    'Somali hedgehog',
    'Somali serotine',
    'Somali shrew',
    'Sonoma chipmunk',
    'Sooty mangabey',
    'Sooty roundleaf bat',
    'Soprano pipistrelle',
    'Sorensen\'s leaf-nosed bat',
    'South African pouched mouse',
    'South African springhare',
    'South American coati',
    'South American fur seal',
    'South American gray fox',
    'South American sea lion',
    'South American tapir',
    'South Andean deer',
    'South Asian river dolphin',
    'South China tiger',
    'Southeast Asian shrew',
    'Southeastern four-eyed opossum',
    'Southeastern myotis',
    'Southeastern pocket gopher',
    'Southeastern shrew',
    'Southern African hedgehog',
    'Southern African vlei rat',
    'Southern Amazon red squirrel',
    'Southern Palawan tree squirrel',
    'Southern Pilbara rock goanna',
    'Southern Plains woodrat',
    'Southern big-eared brown bat',
    'Southern big-eared mouse',
    'Southern birch mouse',
    'Southern bog lemming',
    'Southern bottlenose whale',
    'Southern boubou',
    'Southern brown bandicoot',
    'Southern brown howler',
    'Southern common cuscus',
    'Southern cotton rat',
    'Southern dog-faced bat',
    'Southern double-collared sunbird',
    'Southern elephant seal',
    'Southern flying squirrel',
    'Southern giant slender-tailed cloud rat',
    'Southern giraffe',
    'Southern grasshopper mouse',
    'Southern ground hornbill',
    'Southern hairy-nosed wombat',
    'Southern lapwing',
    'Southern lesser bamboo lemur',
    'Southern long-nosed armadillo',
    'Southern long-nosed bat',
    'Southern marsupial mole',
    'Southern mountain cavy',
    'Southern multimammate mouse',
    'Southern muriqui',
    'Southern naked-tailed armadillo',
    'Southern needle-clawed bushbaby',
    'Southern ningaui',
    'Southern pig-tailed macaque',
    'Southern plains gray langur',
    'Southern pocket gopher',
    'Southern red-backed vole',
    'Southern reedbuck',
    'Southern right whale',
    'Southern river otter',
    'Southern screamer',
    'Southern short-tailed shrew',
    'Southern spotted skunk',
    'Southern tamandua',
    'Southern three-banded armadillo',
    'Southern tree hyrax',
    'Southern viscacha',
    'Southern white-breasted hedgehog',
    'Southern white-cheeked gibbon',
    'Southern white-crowned shrike',
    'Southern woolly lemur',
    'Southern yellow bat',
    'Southwestern myotis',
    'Southwestern water vole',
    'Sowell\'s short-tailed bat',
    'Spanish mole',
    'Speckled dasyure',
    'Speckled ground squirrel',
    'Spectacled bear',
    'Spectacled caiman',
    'Spectacled dormouse',
    'Spectacled flying fox',
    'Spectacled hare-wallaby',
    'Spectral bat',
    'Spectral tarsier',
    'Speke\'s gazelle',
    'Speke\'s pectinator',
    'Spencer\'s goanna',
    'Sperm whale',
    'Spermophilus relictus',
    'Spinifex hopping mouse',
    'Spiny-tailed monitor',
    'Spiny long-footed rat',
    'Spiny pocket mouse',
    'Spix\'s disk-winged bat',
    'Spix\'s night monkey',
    'Spix\'s red-handed howler',
    'Spix\'s yellow-toothed cavy',
    'Sportive lemur',
    'Spotted-necked otter',
    'Spotted-winged fruit bat',
    'Spotted bat',
    'Spotted free-tailed bat',
    'Spotted giant flying squirrel',
    'Spotted ground squirrel',
    'Spotted hyena',
    'Spotted linsang',
    'Spotted seal',
    'Springbok',
    'Spur-winged goose',
    'Spurred roundleaf bat',
    'Squirrel glider',
    'Sri Lankan leopard',
    'Sri Lankan long-tailed shrew',
    'Sri Lankan sambar deer',
    'Sri Lankan shrew',
    'Sri Lankan spotted chevrotain',
    'Star-nosed mole',
    'Steadfast tube-nosed fruit bat',
    'Steenbok',
    'Steere\'s spiny rat',
    'Stein\'s cuscus',
    'Steller sea lion',
    'Steppe field mouse',
    'Steppe lemming',
    'Steppe pika',
    'Steppe polecat',
    'Stoat',
    'Stoliczka\'s trident bat',
    'Stolička\'s mountain vole',
    'Stone sheep',
    'Storr\'s monitor',
    'Straw-coloured fruit bat',
    'Striated heron',
    'Stripe-faced dunnart',
    'Stripe-headed round-eared bat',
    'Stripe-necked mongoose',
    'Stripe-tailed goanna',
    'Striped bandicoot',
    'Striped bush squirrel',
    'Striped dolphin',
    'Striped field mouse',
    'Striped hairy-nosed bat',
    'Striped hog-nosed skunk',
    'Striped hyena',
    'Striped leaf-nosed bat',
    'Striped polecat',
    'Striped possum',
    'Striped skunk',
    'Stuhlmann\'s golden mole',
    'Stump-tailed macaque',
    'Stump-tailed porcupine',
    'Subantarctic fur seal',
    'Subtropical antechinus',
    'Sugar glider',
    'Sulawesi bear cuscus',
    'Sulawesi dwarf cuscus',
    'Sulawesi flying fox',
    'Sulawesi harpy fruit bat',
    'Sulawesi horseshoe bat',
    'Sulawesi naked-backed fruit bat',
    'Sulawesi palm civet',
    'Sulawesi rousette',
    'Sulawesi shrew',
    'Sulawesi stripe-faced fruit bat',
    'Sulawesi tiny shrew',
    'Sulawesi white-handed shrew',
    'Sulphur-crested cockatoo',
    'Sumatran clouded leopard',
    'Sumatran elephant',
    'Sumatran giant shrew',
    'Sumatran long-tailed shrew',
    'Sumatran orangutan',
    'Sumatran porcupine',
    'Sumatran serow',
    'Sumatran striped rabbit',
    'Sumatran tiger',
    'Sumba roundleaf bat',
    'Sumichrast\'s vesper rat',
    'Summit rat',
    'Sun-tailed monkey',
    'Sun bear',
    'Sunda Island tiger',
    'Sunda clouded leopard',
    'Sunda flying fox',
    'Sunda flying lemur',
    'Sunda pangolin',
    'Sunda porcupine',
    'Sunda shrew',
    'Sunda slow loris',
    'Sunda stink badger',
    'Sundevall\'s jird',
    'Sundevall\'s roundleaf bat',
    'Suni',
    'Superb starling',
    'Swainson\'s spurfowl',
    'Swallow-tailed gull',
    'Swamp antechinus',
    'Swamp musk shrew',
    'Swamp rabbit',
    'Swamp wallaby',
    'Swayne\'s hartebeest',
    'Swift fox',
    'Swift fruit bat',
    'Swinhoe\'s striped squirrel',
    'Swinny\'s horseshoe bat',
    'Szechwan myotis',
    'São Tomé collared fruit bat',
    'São Tomé shrew',
    'Taiga shrew',
    'Taiga vole',
    'Tailed tailless bat',
    'Tailless fruit bat',
    'Tailless tenrec',
    'Taita shrew',
    'Taiva shrew tenrec',
    'Taiwan field mouse',
    'Taiwan serow',
    'Taiwan vole',
    'Taiwanese brown-toothed shrew',
    'Taiwanese mole shrew',
    'Takin',
    'Talamancan small-eared shrew',
    'Talamancan yellow-shouldered bat',
    'Talaud bear cuscus',
    'Talaud flying fox',
    'Talazac\'s shrew tenrec',
    'Tamaraw',
    'Tamarisk jird',
    'Tammar wallaby',
    'Tamá small-eared shrew',
    'Tana River mangabey',
    'Tanala tufted-tailed rat',
    'Tantalus monkey',
    'Tanzanian shrew',
    'Tapanuli orangutan',
    'Tapeti',
    'Tarai gray langur',
    'Tarantula',
    'Tarbagan marmot',
    'Tarella shrew',
    'Taruca',
    'Tasmanian devil',
    'Tasmanian pademelon',
    'Tasmanian pygmy possum',
    'Tate\'s triok',
    'Tate\'s woolly mouse opossum',
    'Tatra pine vole',
    'Tawny-bellied cotton rat',
    'Tawny eagle',
    'Tawny frogmouth',
    'Tayra',
    'Tehuantepec jackrabbit',
    'Telefomin cuscus',
    'Telford\'s shrew',
    'Temminck\'s flying fox',
    'Temminck\'s mouse',
    'Temminck\'s red colobus',
    'Temminck\'s trident bat',
    'Temotu flying fox',
    'Tenkile',
    'Tent-making bat',
    'Texas antelope squirrel',
    'Texas pocket gopher',
    'Thai horseshoe bat',
    'Thailand roundleaf bat',
    'Thalia\'s shrew',
    'Theobald\'s tomb bat',
    'Therese\'s shrew',
    'Thick-spined porcupine',
    'Thick-tailed pygmy jerboa',
    'Thick-tailed shrew',
    'Thick-tailed three-toed jerboa',
    'Thick-thumbed myotis',
    'Thirteen-lined ground squirrel',
    'Thollon\'s red colobus',
    'Thomas\'s big-eared brown bat',
    'Thomas\'s broad-nosed bat',
    'Thomas\'s bushbaby',
    'Thomas\'s horseshoe bat',
    'Thomas\'s langur',
    'Thomas\'s nectar bat',
    'Thomas\'s pika',
    'Thomas\'s sac-winged bat',
    'Thomas\'s shaggy bat',
    'Thomas\'s shrew tenrec',
    'Thomas\'s yellow bat',
    'Thomasomys ucucha',
    'Thomson\'s gazelle',
    'Thorold\'s deer',
    'Three-banded plover',
    'Three-striped dasyure',
    'Three-striped ground squirrel',
    'Three-striped night monkey',
    'Thumbless bat',
    'Tibetan antelope',
    'Tibetan macaque',
    'Tickell\'s bat',
    'Tien Shan shrew',
    'Tiger',
    'Tiger quoll',
    'Tiger snake',
    'Tilda\'s yellow-shouldered bat',
    'Tiliqua gigas',
    'Tiliqua rugosa',
    'Tiliqua scincoides',
    'Timorese horseshoe bat',
    'Tiny serotine',
    'Tiny yellow bat',
    'Titania\'s woolly bat',
    'Togian babirusa',
    'Tokay gecko',
    'Tokunoshima spiny rat',
    'Tolai hare',
    'Toltec fruit-eating bat',
    'Tome\'s spiny rat',
    'Tomes\'s sword-nosed bat',
    'Tonkean macaque',
    'Tonkin snub-nosed monkey',
    'Toque macaque',
    'Townsend\'s big-eared bat',
    'Townsend\'s chipmunk',
    'Townsend\'s ground squirrel',
    'Townsend\'s mole',
    'Townsend\'s vole',
    'Transbaikal zokor',
    'Transcaucasian water shrew',
    'Tree bat',
    'Trefoil-toothed giant rat',
    'Trefoil horseshoe bat',
    'Tres Marias rabbit',
    'Tricolored big-eared bat',
    'Trident bat',
    'Trinidad spiny pocket mouse',
    'Trinidadian funnel-eared bat',
    'Tristram\'s jird',
    'Tropical antechinus',
    'Troughton\'s sheath-tailed bat',
    'Trowbridge\'s shrew',
    'True\'s shrew mole',
    'Trumpeter swan',
    'Tschudi\'s slender opossum',
    'Tschudi\'s yellow-shouldered bat',
    'Tufted capuchin',
    'Tufted deer',
    'Tufted gray langur',
    'Tufted ground squirrel',
    'Tufted pygmy squirrel',
    'Tundra shrew',
    'Tundra vole',
    'Turbo shrew',
    'Turkestan red pika',
    'Turkey vulture',
    'Turkish hamster',
    'Turuchan pika',
    'Typical striped grass mouse',
    'Tyrant flycatcher',
    'Udzungwa red colobus',
    'Ugandan kob',
    'Ugandan red colobus',
    'Uinta chipmunk',
    'Uinta ground squirrel',
    'Uluguru bushbaby',
    'Umboi tube-nosed fruit bat',
    'Unadorned rock-wallaby',
    'Underwood\'s bonneted bat',
    'Underwood\'s long-tongued bat',
    'Ungava collared lemming',
    'Unicolored Oldfield mouse',
    'Unstriped ground squirrel',
    'Ural field mouse',
    'Urial',
    'Ursine colobus',
    'Ursine howler',
    'Ursine tree-kangaroo',
    'Usambara shrew',
    'Ussuri tube-nosed bat',
    'Ussuri white-toothed shrew',
    'Uta Hick\'s bearded saki',
    'Utah prairie dog',
    'Vagrant shrew',
    'Van Gelder\'s bat',
    'Van Zyl\'s golden mole',
    'Vancouver Island marmot',
    'Vanessa indica',
    'Vanikoro flying fox',
    'Vanuatu flying fox',
    'Vaquita',
    'Variegated squirrel',
    'Veldkamp\'s dwarf epauletted fruit bat',
    'Velvety free-tailed bat',
    'Velvety fruit-eating bat',
    'Veracruz shrew',
    'Verapaz shrew',
    'Verreaux\'s sifaka',
    'Vervet monkey',
    'Vicuña',
    'Villa\'s gray shrew',
    'Violet-eared waxbill',
    'Virginia opossum',
    'Visayan spotted deer',
    'Visayan warty pig',
    'Voalavoanala',
    'Vogelkop ringtail possum',
    'Voi shrew',
    'Volcano rabbit',
    'Volcano shrew',
    'Von der Decken\'s sifaka',
    'Voracious shrew',
    'Wagner\'s bonneted bat',
    'Wagner\'s mustached bat',
    'Wahlberg\'s epauletted fruit bat',
    'Waigeou cuscus',
    'Walia ibex',
    'Wall-roosting mouse-eared bat',
    'Wandering small-eared shrew',
    'Washington ground squirrel',
    'Water chevrotain',
    'Water deer',
    'Water opossum',
    'Waterbuck',
    'Waterhouse\'s leaf-nosed bat',
    'Waters\'s gerbil',
    'Wattled crane',
    'Waved albatross',
    'Weasel sportive lemur',
    'Web-footed tenrec',
    'Webb\'s tufted-tailed rat',
    'Weddell\'s saddle-back tamarin',
    'Weddell seal',
    'Wedge-capped capuchin',
    'Welwitsch\'s bat',
    'West African long-tailed shrew',
    'West African pygmy shrew',
    'West Caucasian tur',
    'Western barred bandicoot',
    'Western blue-tongued lizard',
    'Western broad-nosed bat',
    'Western brush wallaby',
    'Western chimpanzee',
    'Western dwarf squirrel',
    'Western gorilla',
    'Western gray squirrel',
    'Western grey kangaroo',
    'Western hartebeest',
    'Western harvest mouse',
    'Western heather vole',
    'Western hoolock gibbon',
    'Western jumping mouse',
    'Western lesser bamboo lemur',
    'Western long-tongued bat',
    'Western lowland gorilla',
    'Western lowland olingo',
    'Western mastiff bat',
    'Western mouse',
    'Western naked-backed fruit bat',
    'Western nectar bat',
    'Western purple-faced langur',
    'Western pygmy marmoset',
    'Western pygmy possum',
    'Western quoll',
    'Western red-backed vole',
    'Western red colobus',
    'Western ringtail possum',
    'Western rock elephant shrew',
    'Western sheath-tailed bat',
    'Western small-footed bat',
    'Western spotted skunk',
    'Western sucker-footed bat',
    'Western swamphen',
    'Western tree hyrax',
    'Western woolly lemur',
    'Western yellow bat',
    'Weyland ringtail possum',
    'Weyns\'s duiker',
    'Whiptail wallaby',
    'Whiskered bat',
    'Whiskered flying squirrel',
    'Whitaker\'s shrew',
    'White-beaked dolphin',
    'White-bellied Luzon tree rat',
    'White-bellied big-eared bat',
    'White-bellied duiker',
    'White-bellied fat-tailed mouse opossum',
    'White-bellied musk deer',
    'White-bellied sea eagle',
    'White-bellied slender opossum',
    'White-bellied spider monkey',
    'White-bellied woolly mouse opossum',
    'White-bellied yellow bat',
    'White-browed owl',
    'White-browed sparrow-weaver',
    'White-cheeked pintail',
    'White-cheeked spider monkey',
    'White-coated titi',
    'White-collared fruit bat',
    'White-eared opossum',
    'White-eared titi',
    'White-faced saki',
    'White-faced spiny tree-rat',
    'White-faced whistling duck',
    'White-footed climbing mouse',
    'White-footed dunnart',
    'White-footed mouse',
    'White-footed saki',
    'White-footed sportive lemur',
    'White-footed tamarin',
    'White-footed vole',
    'White-fronted bee-eater',
    'White-fronted capuchin',
    'White-fronted surili',
    'White-headed langur',
    'White-headed lemur',
    'White-headed marmoset',
    'White-headed vulture',
    'White-lined broad-nosed bat',
    'White-lipped peccary',
    'White-lipped tamarin',
    'White-mantled tamarin',
    'White-necked raven',
    'White-nosed coati',
    'White-nosed saki',
    'White-rumped vulture',
    'White-sided jackrabbit',
    'White-spined Atlantic spiny rat',
    'White-striped dorcopsis',
    'White-striped free-tailed bat',
    'White-tailed antelope squirrel',
    'White-tailed antsangy',
    'White-tailed deer',
    'White-tailed dunnart',
    'White-tailed jackrabbit',
    'White-tailed mole',
    'White-tailed mongoose',
    'White-tailed prairie dog',
    'White-tailed titi',
    'White-thighed surili',
    'White-throated guenon',
    'White-throated kingfisher',
    'White-throated monitor',
    'White-throated robin',
    'White-throated round-eared bat',
    'White-throated toucan',
    'White-throated woodrat',
    'White-tipped tufted-tailed rat',
    'White-winged dog-like bat',
    'White-winged dove',
    'White-winged flying fox',
    'White-winged tern',
    'White-winged vampire bat',
    'White marmoset',
    'White rhinoceros',
    'White stork',
    'Whitehead\'s spiny rat',
    'Whitehead\'s woolly bat',
    'Wied\'s marmoset',
    'Wild Bactrian camel',
    'Wild boar',
    'Wild goat',
    'Wild turkey',
    'Wild water buffalo',
    'Wild yak',
    'Wildcat',
    'Wimmer\'s shrew',
    'Woermann\'s bat',
    'Wolf',
    'Wolf spider',
    'Wollaston\'s roundleaf bat',
    'Wolverine',
    'Wongai ningaui',
    'Wood\'s slit-faced bat',
    'Wood lemming',
    'Wood mouse',
    'Wood sandpiper',
    'Wood sprite gracile opossum',
    'Woodford\'s fruit bat',
    'Woodland dormouse',
    'Woodland jumping mouse',
    'Woodland thicket rat',
    'Woodland vole',
    'Woodlark cuscus',
    'Woolley\'s false antechinus',
    'Woolly-necked stork',
    'Woolly flying squirrel',
    'Woolly giant rat',
    'Woolly hare',
    'Woolly horseshoe bat',
    'Woolly mouse opossum',
    'Woosnam\'s broad-headed mouse',
    'Woylie',
    'Wright\'s sportive lemur',
    'Wrinkle-faced bat',
    'Wyoming ground squirrel',
    'Wyoming pocket gopher',
    'Xanthippe\'s shrew',
    'Yakushima macaque',
    'Yanbaru whiskered bat',
    'Yankari shrew',
    'Yarkand hare',
    'Yellow-backed duiker',
    'Yellow-bellied glider',
    'Yellow-bellied marmot',
    'Yellow-bellied sheath-tailed bat',
    'Yellow-bellied weasel',
    'Yellow-billed stork',
    'Yellow-cheeked gibbon',
    'Yellow-crowned brush-tailed rat',
    'Yellow-crowned night heron',
    'Yellow-faced horseshoe bat',
    'Yellow-faced pocket gopher',
    'Yellow-footed antechinus',
    'Yellow-footed rock-wallaby',
    'Yellow-headed caracara',
    'Yellow-necked mouse',
    'Yellow-necked spurfowl',
    'Yellow-nosed cotton rat',
    'Yellow-pine chipmunk',
    'Yellow-rumped leaf-eared mouse',
    'Yellow-rumped siskin',
    'Yellow-sided opossum',
    'Yellow-spotted monitor',
    'Yellow-spotted rock hyrax',
    'Yellow-striped chevrotain',
    'Yellow-tailed rat',
    'Yellow-tailed woolly monkey',
    'Yellow-throated big-eared bat',
    'Yellow-throated marten',
    'Yellow-throated sandgrouse',
    'Yellow-winged bat',
    'Yellow baboon',
    'Yellow golden mole',
    'Yellow ground squirrel',
    'Yellow mongoose',
    'Yellowish myotis',
    'Yonenaga\'s Atlantic spiny rat',
    'Yucatan brown brocket',
    'Yucatan small-eared shrew',
    'Yucatan spider monkey',
    'Yucatan squirrel',
    'Yucatan yellow bat',
    'Yuma myotis',
    'Yunnan hare',
    'Zacatecan deer mouse',
    'Zacatecas shrew',
    'Zaisan mole vole',
    'Zanzibar bushbaby',
    'Zanzibar red colobus',
    'Zarudny\'s rock shrew',
    'Zebra duiker',
    'Zempoaltepec',
    'Zenker\'s fruit bat',
    'Ziama horseshoe bat'
];
